/**
 * Seed budget data — ported from dashboard mock data.
 *
 * Project ID mapping:
 *   sandbox-001    -> belmont
 *   greenfield-002 -> wieland
 *   (new)          -> lasalle
 *
 * All monetary values are numbers. All dates are ISO strings.
 *
 * SEED_BUDGET_CATEGORIES contains the category-level rows.
 * SEED_BUDGET_LINE_ITEMS contains line items, keyed to their parent
 * category via a composite (projectId + costCode) reference.
 */

// ──────────────────────────────────────────────
// Budget Categories
// ──────────────────────────────────────────────

export const SEED_BUDGET_CATEGORIES = [
  // ════════════════════════════════════════════════
  // BELMONT — Mixed-Use Development
  // ════════════════════════════════════════════════
  {
    projectId: 'belmont',
    costCode: '03-00',
    label: 'Concrete',
    original: 620000,
    current: 620000,
    spent: 510000,
    remaining: 110000,
    potential: 0,
    linkedTaskIds: [],
    attachments: [
      { type: 'contract', label: 'Concrete subcontract', url: '#doc-concrete-contract' },
      { type: 'spec', label: 'ACI 318 mix design', url: '#doc-concrete-spec' },
    ],
  },
  {
    projectId: 'belmont',
    costCode: '06-00',
    label: 'Millwork & Woodwork',
    original: 185000,
    current: 185000,
    spent: 92000,
    remaining: 93000,
    potential: 0,
    linkedTaskIds: ['SUB-013'],
    attachments: [],
  },
  {
    projectId: 'belmont',
    costCode: '09-00',
    label: 'Finishes',
    original: 340000,
    current: 340000,
    spent: 245000,
    remaining: 95000,
    potential: 8000,
    linkedTaskIds: ['DEC-006'],
    attachments: [],
  },
  {
    projectId: 'belmont',
    costCode: '09-30',
    label: 'Tile & Stone',
    original: 280000,
    current: 280000,
    spent: 168000,
    remaining: 112000,
    potential: 0,
    linkedTaskIds: ['RFI-047', 'DEC-005', 'LT-005'],
    attachments: [],
  },
  {
    projectId: 'belmont',
    costCode: '14-00',
    label: 'Elevators',
    original: 410000,
    current: 410000,
    spent: 328000,
    remaining: 82000,
    potential: 0,
    linkedTaskIds: ['SUB-011', 'LT-012'],
    attachments: [],
  },
  {
    projectId: 'belmont',
    costCode: '23-00',
    label: 'HVAC',
    original: 680000,
    current: 698400,
    spent: 558720,
    remaining: 139680,
    potential: 18400,
    linkedTaskIds: ['RFI-044', 'PCO-011', 'INV-CM-2267', 'WC-001'],
    attachments: [
      { type: 'contract', label: 'HVAC subcontract', url: '#doc-hvac-contract' },
      { type: 'spec', label: 'Mechanical spec 23 00 00', url: '#doc-hvac-spec' },
    ],
  },
  {
    projectId: 'belmont',
    costCode: '26-00',
    label: 'Electrical',
    original: 520000,
    current: 554200,
    spent: 443360,
    remaining: 110840,
    potential: 34200,
    linkedTaskIds: ['PCO-009', 'INV-8834'],
    attachments: [
      { type: 'contract', label: 'Electrical subcontract', url: '#doc-elec-contract' },
    ],
  },
  {
    projectId: 'belmont',
    costCode: '31-00',
    label: 'Earthwork',
    original: 180000,
    current: 180000,
    spent: 180000,
    remaining: 0,
    potential: 0,
    linkedTaskIds: [],
    attachments: [],
  },
  {
    projectId: 'belmont',
    costCode: '07-00',
    label: 'Waterproofing',
    original: 145000,
    current: 145000,
    spent: 98000,
    remaining: 47000,
    potential: 0,
    linkedTaskIds: ['RFI-048'],
    attachments: [],
  },
  {
    projectId: 'belmont',
    costCode: '32-00',
    label: 'Exterior / Landscape',
    original: 210000,
    current: 175800,
    spent: 140640,
    remaining: 35160,
    potential: 48000,
    linkedTaskIds: [],
    attachments: [],
  },
  {
    projectId: 'belmont',
    costCode: 'GEN',
    label: 'General Conditions',
    original: 645000,
    current: 645000,
    spent: 524340,
    remaining: 120660,
    potential: 0,
    linkedTaskIds: ['PA-005'],
    attachments: [],
  },

  // ════════════════════════════════════════════════
  // WIELAND — Retail Center
  // ════════════════════════════════════════════════
  {
    projectId: 'wieland',
    costCode: '31-00',
    label: 'Earthwork & Grading',
    original: 320000,
    current: 348000,
    spent: 248000,
    remaining: 100000,
    potential: 28000,
    linkedTaskIds: ['GF-PCO-001', 'GF-INV-001'],
    attachments: [],
  },
  {
    projectId: 'wieland',
    costCode: '05-00',
    label: 'Structural Steel',
    original: 480000,
    current: 480000,
    spent: 96000,
    remaining: 384000,
    potential: 0,
    linkedTaskIds: ['GF-SUB-001', 'GF-LT-001'],
    attachments: [],
  },
  {
    projectId: 'wieland',
    costCode: '03-00',
    label: 'Concrete (Foundations)',
    original: 280000,
    current: 280000,
    spent: 112000,
    remaining: 168000,
    potential: 0,
    linkedTaskIds: [],
    attachments: [],
  },
  {
    projectId: 'wieland',
    costCode: '32-00',
    label: 'Site / Parking',
    original: 220000,
    current: 220000,
    spent: 0,
    remaining: 220000,
    potential: 45000,
    linkedTaskIds: ['GF-DEC-001'],
    attachments: [],
  },
  {
    projectId: 'wieland',
    costCode: '08-00',
    label: 'Storefront & Glazing',
    original: 185000,
    current: 185000,
    spent: 0,
    remaining: 185000,
    potential: 0,
    linkedTaskIds: ['GF-RFI-001'],
    attachments: [],
  },
  {
    projectId: 'wieland',
    costCode: 'GEN',
    label: 'General Conditions',
    original: 315000,
    current: 315000,
    spent: 30000,
    remaining: 285000,
    potential: 0,
    linkedTaskIds: [],
    attachments: [],
  },

  // ════════════════════════════════════════════════
  // LASALLE — Office Renovation
  // ════════════════════════════════════════════════
  {
    projectId: 'lasalle',
    costCode: 'GEN',
    label: 'General Conditions',
    original: 180000,
    current: 180000,
    spent: 18000,
    remaining: 162000,
    potential: 0,
    linkedTaskIds: [],
    attachments: [],
  },
  {
    projectId: 'lasalle',
    costCode: '02-00',
    label: 'Interior Demo & Abatement',
    original: 145000,
    current: 145000,
    spent: 38500,
    remaining: 106500,
    potential: 0,
    linkedTaskIds: ['LS-INV-001'],
    attachments: [],
  },
  {
    projectId: 'lasalle',
    costCode: '09-00',
    label: 'Finishes',
    original: 310000,
    current: 310000,
    spent: 0,
    remaining: 310000,
    potential: 0,
    linkedTaskIds: ['LS-SUB-001'],
    attachments: [],
  },
];

// ──────────────────────────────────────────────
// Budget Line Items
// ──────────────────────────────────────────────
// Each line item references its parent category via
// (projectId, costCode). The seed orchestrator should
// look up the generated category id before inserting.
// ──────────────────────────────────────────────

export const SEED_BUDGET_LINE_ITEMS = [
  // ════════════════════════════════════════════════
  // BELMONT — Mixed-Use Development
  // ════════════════════════════════════════════════

  // Concrete (03-00)
  {
    id: 'BM-03-01',
    projectId: 'belmont',
    categoryCostCode: '03-00',
    costCode: '03-10',
    description: 'Foundations — footings & grade beams',
    costType: 'M&L',
    unitPrice: 185,
    quantity: 2000,
    unitType: 'CY',
    budget: 370000,
    previousPaid: 320000,
    due: 50000,
    percentComplete: 100,
    remaining: 0,
    co: 0,
    pco: 0,
    actual: 370000,
    attachments: [
      { type: 'drawing', label: 'Foundation plan S-101', url: '#dwg-s101' },
    ],
  },
  {
    id: 'BM-03-02',
    projectId: 'belmont',
    categoryCostCode: '03-00',
    costCode: '03-30',
    description: 'Elevated slabs — post-tension',
    costType: 'M&L',
    unitPrice: 25,
    quantity: 10000,
    unitType: 'SF',
    budget: 250000,
    previousPaid: 140000,
    due: 0,
    percentComplete: 56,
    remaining: 110000,
    co: 0,
    pco: 0,
    actual: 140000,
    attachments: [
      { type: 'drawing', label: 'PT slab layout S-201', url: '#dwg-s201' },
      { type: 'photo', label: 'L3 slab pour — Jan 15', url: '#photo-slab-l3' },
    ],
  },

  // Millwork & Woodwork (06-00)
  {
    id: 'BM-06-01',
    projectId: 'belmont',
    categoryCostCode: '06-00',
    costCode: '06-20',
    description: 'Custom cabinetry — lobby & amenity',
    costType: 'M',
    unitPrice: 450,
    quantity: 200,
    unitType: 'LF',
    budget: 90000,
    previousPaid: 45000,
    due: 0,
    percentComplete: 50,
    remaining: 45000,
    co: 0,
    pco: 0,
    actual: 45000,
    attachments: [],
  },
  {
    id: 'BM-06-02',
    projectId: 'belmont',
    categoryCostCode: '06-00',
    costCode: '06-40',
    description: 'Architectural woodwork — feature walls',
    costType: 'L',
    unitPrice: 95,
    quantity: 1000,
    unitType: 'SF',
    budget: 95000,
    previousPaid: 47000,
    due: 0,
    percentComplete: 49,
    remaining: 48000,
    co: 0,
    pco: 0,
    actual: 47000,
    attachments: [],
  },

  // Finishes (09-00)
  {
    id: 'BM-09-01',
    projectId: 'belmont',
    categoryCostCode: '09-00',
    costCode: '09-21',
    description: 'Drywall & framing — units',
    costType: 'M&L',
    unitPrice: 8,
    quantity: 22000,
    unitType: 'SF',
    budget: 176000,
    previousPaid: 150000,
    due: 0,
    percentComplete: 85,
    remaining: 26000,
    co: 0,
    pco: 0,
    actual: 150000,
    attachments: [],
  },
  {
    id: 'BM-09-02',
    projectId: 'belmont',
    categoryCostCode: '09-00',
    costCode: '09-65',
    description: 'Resilient flooring — LVP common areas',
    costType: 'M',
    unitPrice: 12,
    quantity: 8000,
    unitType: 'SF',
    budget: 96000,
    previousPaid: 60000,
    due: 0,
    percentComplete: 63,
    remaining: 36000,
    co: 0,
    pco: 8000,
    actual: 60000,
    attachments: [],
  },
  {
    id: 'BM-09-03',
    projectId: 'belmont',
    categoryCostCode: '09-00',
    costCode: '09-91',
    description: 'Painting — interior units',
    costType: 'L',
    unitPrice: 4,
    quantity: 17000,
    unitType: 'SF',
    budget: 68000,
    previousPaid: 35000,
    due: 0,
    percentComplete: 51,
    remaining: 33000,
    co: 0,
    pco: 0,
    actual: 35000,
    attachments: [],
  },

  // Tile & Stone (09-30)
  {
    id: 'BM-093-01',
    projectId: 'belmont',
    categoryCostCode: '09-30',
    costCode: '09-31',
    description: 'Porcelain tile — bathrooms',
    costType: 'M&L',
    unitPrice: 18,
    quantity: 9000,
    unitType: 'SF',
    budget: 162000,
    previousPaid: 100000,
    due: 0,
    percentComplete: 62,
    remaining: 62000,
    co: 0,
    pco: 0,
    actual: 100000,
    attachments: [
      { type: 'spec', label: 'Tile selection schedule', url: '#doc-tile-spec' },
    ],
  },
  {
    id: 'BM-093-02',
    projectId: 'belmont',
    categoryCostCode: '09-30',
    costCode: '09-32',
    description: 'Natural stone — lobby feature',
    costType: 'M',
    unitPrice: 65,
    quantity: 1815,
    unitType: 'SF',
    budget: 118000,
    previousPaid: 68000,
    due: 0,
    percentComplete: 58,
    remaining: 50000,
    co: 0,
    pco: 0,
    actual: 68000,
    attachments: [],
  },

  // Elevators (14-00)
  {
    id: 'BM-14-01',
    projectId: 'belmont',
    categoryCostCode: '14-00',
    costCode: '14-21',
    description: 'Passenger elevators (2) — supply & install',
    costType: 'M&L',
    unitPrice: 195000,
    quantity: 2,
    unitType: 'EA',
    budget: 390000,
    previousPaid: 312000,
    due: 0,
    percentComplete: 80,
    remaining: 78000,
    co: 0,
    pco: 0,
    actual: 312000,
    attachments: [
      { type: 'contract', label: 'Elevator purchase agreement', url: '#doc-elev-contract' },
      { type: 'spec', label: 'Cab finish spec', url: '#doc-elev-spec' },
    ],
  },
  {
    id: 'BM-14-02',
    projectId: 'belmont',
    categoryCostCode: '14-00',
    costCode: '14-90',
    description: 'Elevator cab finishes',
    costType: 'M',
    unitPrice: 10000,
    quantity: 2,
    unitType: 'EA',
    budget: 20000,
    previousPaid: 16000,
    due: 0,
    percentComplete: 80,
    remaining: 4000,
    co: 0,
    pco: 0,
    actual: 16000,
    attachments: [],
  },

  // HVAC (23-00)
  {
    id: 'BM-23-01',
    projectId: 'belmont',
    categoryCostCode: '23-00',
    costCode: '23-05',
    description: 'Ductwork — supply & return',
    costType: 'M&L',
    unitPrice: 22,
    quantity: 18000,
    unitType: 'LF',
    budget: 396000,
    previousPaid: 320000,
    due: 0,
    percentComplete: 81,
    remaining: 76000,
    co: 18400,
    pco: 0,
    actual: 338400,
    attachments: [
      { type: 'drawing', label: 'Duct layout M-301', url: '#dwg-m301' },
      { type: 'photo', label: 'L3 duct install progress', url: '#photo-duct-l3' },
    ],
  },
  {
    id: 'BM-23-02',
    projectId: 'belmont',
    categoryCostCode: '23-00',
    costCode: '23-81',
    description: 'Rooftop units (RTUs)',
    costType: 'E',
    unitPrice: 42000,
    quantity: 4,
    unitType: 'EA',
    budget: 168000,
    previousPaid: 134400,
    due: 0,
    percentComplete: 80,
    remaining: 33600,
    co: 0,
    pco: 18400,
    actual: 134400,
    attachments: [],
  },
  {
    id: 'BM-23-03',
    projectId: 'belmont',
    categoryCostCode: '23-00',
    costCode: '23-09',
    description: 'Controls & TAB',
    costType: 'L',
    unitPrice: 1,
    quantity: 134400,
    unitType: 'LS',
    budget: 134400,
    previousPaid: 85920,
    due: 0,
    percentComplete: 64,
    remaining: 48480,
    co: 0,
    pco: 0,
    actual: 85920,
    attachments: [],
  },

  // Electrical (26-00)
  {
    id: 'BM-26-01',
    projectId: 'belmont',
    categoryCostCode: '26-00',
    costCode: '26-05',
    description: 'Rough-in — conduit & wire',
    costType: 'M&L',
    unitPrice: 16,
    quantity: 20000,
    unitType: 'LF',
    budget: 320000,
    previousPaid: 270000,
    due: 0,
    percentComplete: 84,
    remaining: 50000,
    co: 34200,
    pco: 0,
    actual: 304200,
    attachments: [
      { type: 'drawing', label: 'Electrical plan E-201', url: '#dwg-e201' },
    ],
  },
  {
    id: 'BM-26-02',
    projectId: 'belmont',
    categoryCostCode: '26-00',
    costCode: '26-51',
    description: 'Lighting fixtures — units & common',
    costType: 'M',
    unitPrice: 120,
    quantity: 1200,
    unitType: 'EA',
    budget: 144000,
    previousPaid: 108000,
    due: 0,
    percentComplete: 75,
    remaining: 36000,
    co: 0,
    pco: 0,
    actual: 108000,
    attachments: [],
  },
  {
    id: 'BM-26-03',
    projectId: 'belmont',
    categoryCostCode: '26-00',
    costCode: '26-27',
    description: 'Switchgear & panels',
    costType: 'E',
    unitPrice: 15200,
    quantity: 6,
    unitType: 'EA',
    budget: 91200,
    previousPaid: 65360,
    due: 0,
    percentComplete: 72,
    remaining: 25840,
    co: 0,
    pco: 34200,
    actual: 65360,
    attachments: [],
  },

  // Earthwork (31-00)
  {
    id: 'BM-31-01',
    projectId: 'belmont',
    categoryCostCode: '31-00',
    costCode: '31-23',
    description: 'Excavation & grading',
    costType: 'M&L',
    unitPrice: 18,
    quantity: 6000,
    unitType: 'CY',
    budget: 108000,
    previousPaid: 108000,
    due: 0,
    percentComplete: 100,
    remaining: 0,
    co: 0,
    pco: 0,
    actual: 108000,
    attachments: [],
  },
  {
    id: 'BM-31-02',
    projectId: 'belmont',
    categoryCostCode: '31-00',
    costCode: '31-25',
    description: 'Backfill & compaction',
    costType: 'L',
    unitPrice: 24,
    quantity: 3000,
    unitType: 'CY',
    budget: 72000,
    previousPaid: 72000,
    due: 0,
    percentComplete: 100,
    remaining: 0,
    co: 0,
    pco: 0,
    actual: 72000,
    attachments: [],
  },

  // Waterproofing (07-00)
  {
    id: 'BM-07-01',
    projectId: 'belmont',
    categoryCostCode: '07-00',
    costCode: '07-11',
    description: 'Below-grade waterproofing membrane',
    costType: 'M&L',
    unitPrice: 9,
    quantity: 10000,
    unitType: 'SF',
    budget: 90000,
    previousPaid: 68000,
    due: 0,
    percentComplete: 76,
    remaining: 22000,
    co: 0,
    pco: 0,
    actual: 68000,
    attachments: [],
  },
  {
    id: 'BM-07-02',
    projectId: 'belmont',
    categoryCostCode: '07-00',
    costCode: '07-62',
    description: 'Flashing & sheet metal',
    costType: 'M',
    unitPrice: 22,
    quantity: 2500,
    unitType: 'LF',
    budget: 55000,
    previousPaid: 30000,
    due: 0,
    percentComplete: 55,
    remaining: 25000,
    co: 0,
    pco: 0,
    actual: 30000,
    attachments: [],
  },

  // Exterior / Landscape (32-00)
  {
    id: 'BM-32-01',
    projectId: 'belmont',
    categoryCostCode: '32-00',
    costCode: '32-12',
    description: 'Hardscape — pavers & curbing',
    costType: 'M&L',
    unitPrice: 14,
    quantity: 8000,
    unitType: 'SF',
    budget: 112000,
    previousPaid: 90000,
    due: 0,
    percentComplete: 80,
    remaining: 22000,
    co: 0,
    pco: 24000,
    actual: 90000,
    attachments: [],
  },
  {
    id: 'BM-32-02',
    projectId: 'belmont',
    categoryCostCode: '32-00',
    costCode: '32-90',
    description: 'Planting & irrigation',
    costType: 'M&L',
    unitPrice: 1,
    quantity: 63800,
    unitType: 'LS',
    budget: 63800,
    previousPaid: 50640,
    due: 0,
    percentComplete: 79,
    remaining: 13160,
    co: 0,
    pco: 24000,
    actual: 50640,
    attachments: [],
  },

  // General Conditions (GEN)
  {
    id: 'BM-GEN-01',
    projectId: 'belmont',
    categoryCostCode: 'GEN',
    costCode: 'GEN-01',
    description: 'Project management staff',
    costType: 'L',
    unitPrice: 85,
    quantity: 4200,
    unitType: 'HR',
    budget: 357000,
    previousPaid: 290000,
    due: 0,
    percentComplete: 81,
    remaining: 67000,
    co: 0,
    pco: 0,
    actual: 290000,
    attachments: [],
  },
  {
    id: 'BM-GEN-02',
    projectId: 'belmont',
    categoryCostCode: 'GEN',
    costCode: 'GEN-02',
    description: 'Temporary facilities & utilities',
    costType: 'M',
    unitPrice: 1,
    quantity: 168000,
    unitType: 'LS',
    budget: 168000,
    previousPaid: 134340,
    due: 0,
    percentComplete: 80,
    remaining: 33660,
    co: 0,
    pco: 0,
    actual: 134340,
    attachments: [],
  },
  {
    id: 'BM-GEN-03',
    projectId: 'belmont',
    categoryCostCode: 'GEN',
    costCode: 'GEN-03',
    description: 'Insurance & bonding',
    costType: 'E',
    unitPrice: 1,
    quantity: 120000,
    unitType: 'LS',
    budget: 120000,
    previousPaid: 100000,
    due: 0,
    percentComplete: 83,
    remaining: 20000,
    co: 0,
    pco: 0,
    actual: 100000,
    attachments: [],
  },

  // ════════════════════════════════════════════════
  // WIELAND — Retail Center
  // ════════════════════════════════════════════════

  // Earthwork & Grading (31-00)
  {
    id: 'WL-31-01',
    projectId: 'wieland',
    categoryCostCode: '31-00',
    costCode: '31-23',
    description: 'Mass grading & export',
    costType: 'M&L',
    unitPrice: 14,
    quantity: 18000,
    unitType: 'CY',
    budget: 252000,
    previousPaid: 200000,
    due: 0,
    percentComplete: 79,
    remaining: 52000,
    co: 28000,
    pco: 0,
    actual: 228000,
    attachments: [
      { type: 'contract', label: 'Grading subcontract', url: '#doc-gf-grading-contract' },
      { type: 'photo', label: 'NW quadrant soil export', url: '#photo-gf-soil' },
    ],
  },
  {
    id: 'WL-31-02',
    projectId: 'wieland',
    categoryCostCode: '31-00',
    costCode: '31-25',
    description: 'Structural fill import & compact',
    costType: 'M&L',
    unitPrice: 24,
    quantity: 4000,
    unitType: 'CY',
    budget: 96000,
    previousPaid: 48000,
    due: 0,
    percentComplete: 50,
    remaining: 48000,
    co: 0,
    pco: 0,
    actual: 48000,
    attachments: [],
  },

  // Structural Steel (05-00)
  {
    id: 'WL-05-01',
    projectId: 'wieland',
    categoryCostCode: '05-00',
    costCode: '05-12',
    description: 'Structural steel — fabrication & erection',
    costType: 'M&L',
    unitPrice: 8500,
    quantity: 45,
    unitType: 'EA',
    budget: 382500,
    previousPaid: 76500,
    due: 0,
    percentComplete: 20,
    remaining: 306000,
    co: 0,
    pco: 0,
    actual: 76500,
    attachments: [
      { type: 'drawing', label: 'Steel framing plan S-100', url: '#dwg-gf-s100' },
      { type: 'spec', label: 'Structural steel spec 05 12 00', url: '#doc-gf-steel-spec' },
    ],
  },
  {
    id: 'WL-05-02',
    projectId: 'wieland',
    categoryCostCode: '05-00',
    costCode: '05-50',
    description: 'Metal decking',
    costType: 'M',
    unitPrice: 6,
    quantity: 16250,
    unitType: 'SF',
    budget: 97500,
    previousPaid: 19500,
    due: 0,
    percentComplete: 20,
    remaining: 78000,
    co: 0,
    pco: 0,
    actual: 19500,
    attachments: [],
  },

  // Concrete — Foundations (03-00)
  {
    id: 'WL-03-01',
    projectId: 'wieland',
    categoryCostCode: '03-00',
    costCode: '03-10',
    description: 'Spread footings & piers',
    costType: 'M&L',
    unitPrice: 175,
    quantity: 1000,
    unitType: 'CY',
    budget: 175000,
    previousPaid: 70000,
    due: 0,
    percentComplete: 40,
    remaining: 105000,
    co: 0,
    pco: 0,
    actual: 70000,
    attachments: [],
  },
  {
    id: 'WL-03-02',
    projectId: 'wieland',
    categoryCostCode: '03-00',
    costCode: '03-30',
    description: 'Slab on grade',
    costType: 'M&L',
    unitPrice: 7,
    quantity: 15000,
    unitType: 'SF',
    budget: 105000,
    previousPaid: 42000,
    due: 0,
    percentComplete: 40,
    remaining: 63000,
    co: 0,
    pco: 0,
    actual: 42000,
    attachments: [],
  },

  // Site / Parking (32-00)
  {
    id: 'WL-32-01',
    projectId: 'wieland',
    categoryCostCode: '32-00',
    costCode: '32-12',
    description: 'Asphalt paving — parking lot',
    costType: 'M&L',
    unitPrice: 5,
    quantity: 28000,
    unitType: 'SF',
    budget: 140000,
    previousPaid: 0,
    due: 0,
    percentComplete: 0,
    remaining: 140000,
    co: 0,
    pco: 45000,
    actual: 0,
    attachments: [],
  },
  {
    id: 'WL-32-02',
    projectId: 'wieland',
    categoryCostCode: '32-00',
    costCode: '32-90',
    description: 'Landscape & irrigation',
    costType: 'M&L',
    unitPrice: 1,
    quantity: 80000,
    unitType: 'LS',
    budget: 80000,
    previousPaid: 0,
    due: 0,
    percentComplete: 0,
    remaining: 80000,
    co: 0,
    pco: 0,
    actual: 0,
    attachments: [],
  },

  // Storefront & Glazing (08-00)
  {
    id: 'WL-08-01',
    projectId: 'wieland',
    categoryCostCode: '08-00',
    costCode: '08-44',
    description: 'Storefront curtain wall system',
    costType: 'M&L',
    unitPrice: 85,
    quantity: 1600,
    unitType: 'SF',
    budget: 136000,
    previousPaid: 0,
    due: 0,
    percentComplete: 0,
    remaining: 136000,
    co: 0,
    pco: 0,
    actual: 0,
    attachments: [
      { type: 'drawing', label: 'Storefront elevation A-301', url: '#dwg-gf-a301' },
    ],
  },
  {
    id: 'WL-08-02',
    projectId: 'wieland',
    categoryCostCode: '08-00',
    costCode: '08-80',
    description: 'Glazing — insulated units',
    costType: 'M',
    unitPrice: 49,
    quantity: 1000,
    unitType: 'SF',
    budget: 49000,
    previousPaid: 0,
    due: 0,
    percentComplete: 0,
    remaining: 49000,
    co: 0,
    pco: 0,
    actual: 0,
    attachments: [],
  },

  // General Conditions (GEN)
  {
    id: 'WL-GEN-01',
    projectId: 'wieland',
    categoryCostCode: 'GEN',
    costCode: 'GEN-01',
    description: 'Site superintendent',
    costType: 'L',
    unitPrice: 75,
    quantity: 2800,
    unitType: 'HR',
    budget: 210000,
    previousPaid: 21000,
    due: 0,
    percentComplete: 10,
    remaining: 189000,
    co: 0,
    pco: 0,
    actual: 21000,
    attachments: [],
  },
  {
    id: 'WL-GEN-02',
    projectId: 'wieland',
    categoryCostCode: 'GEN',
    costCode: 'GEN-02',
    description: 'Temporary facilities & power',
    costType: 'M',
    unitPrice: 1,
    quantity: 105000,
    unitType: 'LS',
    budget: 105000,
    previousPaid: 9000,
    due: 0,
    percentComplete: 9,
    remaining: 96000,
    co: 0,
    pco: 0,
    actual: 9000,
    attachments: [],
  },

  // ════════════════════════════════════════════════
  // LASALLE — Office Renovation
  // ════════════════════════════════════════════════

  // General Conditions (GEN)
  {
    id: 'LS-GEN-01',
    projectId: 'lasalle',
    categoryCostCode: 'GEN',
    costCode: 'GEN-01',
    description: 'Project management & supervision',
    costType: 'L',
    unitPrice: 80,
    quantity: 1500,
    unitType: 'HR',
    budget: 120000,
    previousPaid: 12000,
    due: 0,
    percentComplete: 10,
    remaining: 108000,
    co: 0,
    pco: 0,
    actual: 12000,
    attachments: [],
  },
  {
    id: 'LS-GEN-02',
    projectId: 'lasalle',
    categoryCostCode: 'GEN',
    costCode: 'GEN-02',
    description: 'Temporary protection & utilities',
    costType: 'M',
    unitPrice: 1,
    quantity: 60000,
    unitType: 'LS',
    budget: 60000,
    previousPaid: 6000,
    due: 0,
    percentComplete: 10,
    remaining: 54000,
    co: 0,
    pco: 0,
    actual: 6000,
    attachments: [],
  },

  // Interior Demo & Abatement (02-00)
  {
    id: 'LS-02-01',
    projectId: 'lasalle',
    categoryCostCode: '02-00',
    costCode: '02-41',
    description: 'Selective interior demolition',
    costType: 'L',
    unitPrice: 6,
    quantity: 12000,
    unitType: 'SF',
    budget: 72000,
    previousPaid: 0,
    due: 0,
    percentComplete: 0,
    remaining: 72000,
    co: 0,
    pco: 0,
    actual: 0,
    attachments: [],
  },
  {
    id: 'LS-02-02',
    projectId: 'lasalle',
    categoryCostCode: '02-00',
    costCode: '02-82',
    description: 'Hazmat abatement — asbestos tile & mastic',
    costType: 'M&L',
    unitPrice: 14.6,
    quantity: 5000,
    unitType: 'SF',
    budget: 73000,
    previousPaid: 38500,
    due: 0,
    percentComplete: 53,
    remaining: 34500,
    co: 0,
    pco: 0,
    actual: 38500,
    attachments: [
      { type: 'spec', label: 'Hazmat survey report', url: '#doc-ls-hazmat-survey' },
    ],
  },

  // Finishes (09-00)
  {
    id: 'LS-09-01',
    projectId: 'lasalle',
    categoryCostCode: '09-00',
    costCode: '09-21',
    description: 'Drywall & metal framing — open office',
    costType: 'M&L',
    unitPrice: 9,
    quantity: 18000,
    unitType: 'SF',
    budget: 162000,
    previousPaid: 0,
    due: 0,
    percentComplete: 0,
    remaining: 162000,
    co: 0,
    pco: 0,
    actual: 0,
    attachments: [],
  },
  {
    id: 'LS-09-02',
    projectId: 'lasalle',
    categoryCostCode: '09-00',
    costCode: '09-68',
    description: 'Carpet tile — office & corridors',
    costType: 'M',
    unitPrice: 8,
    quantity: 18500,
    unitType: 'SF',
    budget: 148000,
    previousPaid: 0,
    due: 0,
    percentComplete: 0,
    remaining: 148000,
    co: 0,
    pco: 0,
    actual: 0,
    attachments: [],
  },
];
