/* ══════════════════════════════════════════════════
   Seed Data — Business Module
   Dev Milestones, Fund Draws, Leasing, Events, POS,
   Memberships
   Ported from dashboard mock-business.ts
   sandbox-001 -> belmont, greenfield-002 -> wieland
   ══════════════════════════════════════════════════ */

// ─────────────────────────────────────────────
//  Development Milestones
// ─────────────────────────────────────────────

export const SEED_DEV_MILESTONES = [
  // Belmont
  {
    id: 'sb-dev-001',
    projectId: 'belmont',
    phase: 'Site Acquisition',
    label: 'Site Acquisition — Escrow Close & Title Transfer',
    targetDate: '2025-03-15',
    status: 'completed',
    owner: 'Kuan C.',
    notes: 'Closed on 2.3-acre parcel at 1200 Innovation Blvd.',
  },
  {
    id: 'sb-dev-002',
    projectId: 'belmont',
    phase: 'Entitlement',
    label: 'Entitlement — CUP & Zoning Approval',
    targetDate: '2025-06-01',
    status: 'completed',
    owner: 'Kuan C.',
    notes: 'Conditional use permit approved by City Council 5/28.',
  },
  {
    id: 'sb-dev-003',
    projectId: 'belmont',
    phase: 'Design',
    label: 'Design — Schematic & Design Development',
    targetDate: '2025-09-15',
    status: 'completed',
    owner: 'SHB Studio',
    notes: 'DD package delivered. Owner sign-off received 9/12.',
  },
  {
    id: 'sb-dev-004',
    projectId: 'belmont',
    phase: 'Permitting',
    label: 'Permitting — Building Permit Issuance',
    targetDate: '2025-11-01',
    status: 'completed',
    owner: 'SHB Studio',
    notes: 'Permit B-2025-04821 issued by City.',
  },
  {
    id: 'sb-dev-005',
    projectId: 'belmont',
    phase: 'Pre-Construction',
    label: 'Pre-Construction — Buyout & Mobilization',
    targetDate: '2025-12-15',
    status: 'completed',
    owner: 'Sam W.',
    notes: 'Major trades bought out. Site mobilization complete.',
  },
  {
    id: 'sb-dev-006',
    projectId: 'belmont',
    phase: 'Construction',
    label: 'Construction — Vertical Build & Tenant Improvements',
    targetDate: '2026-08-01',
    status: 'in-progress',
    owner: 'Sam W.',
    notes: 'Superstructure 70% complete. MEP rough-ins underway.',
  },
  {
    id: 'sb-dev-007',
    projectId: 'belmont',
    phase: 'Lease-Up',
    label: 'Lease-Up — Pre-Leasing & Tenant Onboarding',
    targetDate: '2026-06-01',
    status: 'upcoming',
    owner: 'Rachel K.',
    notes: 'Pre-leasing campaign scheduled to launch Q1 2026.',
  },
  {
    id: 'sb-dev-008',
    projectId: 'belmont',
    phase: 'Stabilization',
    label: 'Stabilization — 90% Occupancy Target',
    targetDate: '2027-02-01',
    status: 'upcoming',
    owner: 'Rachel K.',
    notes: 'Target 90% occupancy within 6 months of CO.',
  },

  // Wieland
  {
    id: 'gf-dev-001',
    projectId: 'wieland',
    phase: 'Site Acquisition',
    label: 'Site Acquisition — Land Purchase & Due Diligence',
    targetDate: '2025-10-01',
    status: 'completed',
    owner: 'Kuan C.',
    notes: 'Phase I ESA clear. 4.1-acre site acquired.',
  },
  {
    id: 'gf-dev-002',
    projectId: 'wieland',
    phase: 'Entitlement',
    label: 'Entitlement — Rezoning & Site Plan Approval',
    targetDate: '2026-01-15',
    status: 'completed',
    owner: 'Kuan C.',
    notes: 'Rezoning from C-2 to MU-3 approved. Site plan conditionally approved.',
  },
  {
    id: 'gf-dev-003',
    projectId: 'wieland',
    phase: 'Design',
    label: 'Design — Schematic Design & CD Production',
    targetDate: '2026-04-01',
    status: 'in-progress',
    owner: 'SHB Studio',
    notes: 'Schematic design approved. Construction documents 40% complete.',
  },
  {
    id: 'gf-dev-004',
    projectId: 'wieland',
    phase: 'Permitting',
    label: 'Permitting — Plan Check & Permit Application',
    targetDate: '2026-06-15',
    status: 'upcoming',
    owner: 'SHB Studio',
    notes: 'Submittal planned once CDs reach 90%.',
  },
  {
    id: 'gf-dev-005',
    projectId: 'wieland',
    phase: 'Pre-Construction',
    label: 'Pre-Construction — Bidding & Early Procurement',
    targetDate: '2026-03-15',
    status: 'in-progress',
    owner: 'Sam W.',
    notes: 'Structural steel and curtain wall packages out to bid.',
  },
  {
    id: 'gf-dev-006',
    projectId: 'wieland',
    phase: 'Construction',
    label: 'Construction — Site Work & Vertical Build',
    targetDate: '2027-01-15',
    status: 'upcoming',
    owner: 'Sam W.',
    notes: 'Pending permit issuance. Grading plan ready.',
  },

  // LaSalle
  {
    id: 'ls-dev-001',
    projectId: 'lasalle',
    phase: 'Design',
    label: 'Design — Space Planning & Schematic Design',
    targetDate: '2026-02-15',
    status: 'in-progress',
    owner: 'SHB Studio',
    notes: 'Space plan approved. Schematic design 80% complete.',
  },
  {
    id: 'ls-dev-002',
    projectId: 'lasalle',
    phase: 'Permitting',
    label: 'Permitting — Tenant Improvement Permit Application',
    targetDate: '2026-03-15',
    status: 'upcoming',
    owner: 'SHB Studio',
    notes: 'Pending schematic design completion for permit submittal.',
  },
  {
    id: 'ls-dev-003',
    projectId: 'lasalle',
    phase: 'Pre-Construction',
    label: 'Pre-Construction — Bidding & Subcontractor Selection',
    targetDate: '2026-04-01',
    status: 'upcoming',
    owner: 'Sam W.',
    notes: 'Demo and framing packages to be bid once permit is filed.',
  },
  {
    id: 'ls-dev-004',
    projectId: 'lasalle',
    phase: 'Construction',
    label: 'Construction — Interior Demo & Build-Out',
    targetDate: '2026-06-15',
    status: 'upcoming',
    owner: 'Sam W.',
    notes: 'Target 10-week build-out schedule pending permit.',
  },
];

// ─────────────────────────────────────────────
//  Fund Draws
// ─────────────────────────────────────────────

export const SEED_FUND_DRAWS = [
  // Belmont
  {
    id: 'sb-draw-001',
    projectId: 'belmont',
    drawNumber: 1,
    date: '2025-04-01',
    amount: 2500000,
    status: 'approved',
    description: 'Land acquisition and closing costs',
  },
  {
    id: 'sb-draw-002',
    projectId: 'belmont',
    drawNumber: 2,
    date: '2025-07-15',
    amount: 1750000,
    status: 'approved',
    description: 'Entitlement, design fees, and soft costs',
  },
  {
    id: 'sb-draw-003',
    projectId: 'belmont',
    drawNumber: 3,
    date: '2025-11-01',
    amount: 1500000,
    status: 'approved',
    description: 'Permitting, insurance, and pre-construction services',
  },
  {
    id: 'sb-draw-004',
    projectId: 'belmont',
    drawNumber: 4,
    date: '2026-01-15',
    amount: 1500000,
    status: 'approved',
    description: 'Construction mobilization and initial trade payments',
  },
  {
    id: 'sb-draw-005',
    projectId: 'belmont',
    drawNumber: 5,
    date: '2026-02-10',
    amount: 1500000,
    status: 'pending',
    description: 'Structural steel, concrete, and MEP rough-in progress payment',
  },

  // Wieland
  {
    id: 'gf-draw-001',
    projectId: 'wieland',
    drawNumber: 1,
    date: '2025-10-15',
    amount: 1000000,
    status: 'approved',
    description: 'Land acquisition, due diligence, and Phase I ESA',
  },
  {
    id: 'gf-draw-002',
    projectId: 'wieland',
    drawNumber: 2,
    date: '2026-01-20',
    amount: 600000,
    status: 'submitted',
    description: 'Entitlement fees, design retainer, and early procurement deposits',
  },

  // LaSalle
  {
    id: 'ls-draw-001',
    projectId: 'lasalle',
    drawNumber: 1,
    date: '2026-01-10',
    amount: 150000,
    status: 'approved',
    description: 'Design fees, space planning, and pre-construction services',
  },
  {
    id: 'ls-draw-002',
    projectId: 'lasalle',
    drawNumber: 2,
    date: '2026-03-01',
    amount: 250000,
    status: 'upcoming',
    description: 'Permit fees and initial demo/framing trade mobilization',
  },
];

// ─────────────────────────────────────────────
//  Leasing Units (Belmont only)
// ─────────────────────────────────────────────

export const SEED_LEASING_UNITS = [
  {
    id: 'sb-unit-101',
    projectId: 'belmont',
    unit: '101',
    sqft: 1200,
    status: 'leased',
    tenant: 'Groundwork Coffee Co.',
    monthlyRent: 4500,
    leaseStart: '2026-09-01',
    leaseEnd: '2031-08-31',
  },
  {
    id: 'sb-unit-102',
    projectId: 'belmont',
    unit: '102',
    sqft: 950,
    status: 'pending',
    tenant: 'Forma Pilates Studio',
    monthlyRent: 3800,
    leaseStart: '2026-10-01',
    leaseEnd: '2031-09-30',
  },
  {
    id: 'sb-unit-103',
    projectId: 'belmont',
    unit: '103',
    sqft: 600,
    status: 'available',
    monthlyRent: 2500,
  },
  {
    id: 'sb-unit-104',
    projectId: 'belmont',
    unit: '104',
    sqft: 800,
    status: 'available',
    monthlyRent: 3200,
  },
  {
    id: 'sb-unit-105',
    projectId: 'belmont',
    unit: '105',
    sqft: 1100,
    status: 'leased',
    tenant: 'Vanguard Wealth Advisors',
    monthlyRent: 4200,
    leaseStart: '2026-09-01',
    leaseEnd: '2031-08-31',
  },
  {
    id: 'sb-unit-106',
    projectId: 'belmont',
    unit: '106',
    sqft: 750,
    status: 'pending',
    tenant: 'Borough Barbershop',
    monthlyRent: 2800,
    leaseStart: '2026-11-01',
    leaseEnd: '2029-10-31',
  },
  {
    id: 'sb-unit-107',
    projectId: 'belmont',
    unit: '107',
    sqft: 1000,
    status: 'occupied',
    tenant: 'SHB Group \u2014 Leasing Office',
    monthlyRent: 0,
    leaseStart: '2026-01-15',
    leaseEnd: '2026-12-31',
  },
  {
    id: 'sb-unit-108',
    projectId: 'belmont',
    unit: '108',
    sqft: 650,
    status: 'available',
    monthlyRent: 2700,
  },
];

// ─────────────────────────────────────────────
//  Showroom Events (Belmont only)
// ─────────────────────────────────────────────

export const SEED_SHOWROOM_EVENTS = [
  {
    id: 'sb-evt-001',
    projectId: 'belmont',
    title: 'Belmont Grand Preview \u2014 Broker Open House',
    date: '2026-02-22',
    time: '10:00 AM \u2013 1:00 PM',
    type: 'broker-tour',
    location: 'Belmont Showroom, Unit 107',
    attendees: 35,
    notes: 'Catered lunch. Floor plans, finish boards, and VR walkthrough on display.',
  },
  {
    id: 'sb-evt-002',
    projectId: 'belmont',
    title: 'Investor Quarterly Update \u2014 Q1 2026',
    date: '2026-03-05',
    time: '4:00 PM \u2013 5:30 PM',
    type: 'investor-meeting',
    location: 'SHB Group Conference Room',
    attendees: 12,
    notes: 'Construction progress, draw schedule review, lease-up projections.',
  },
  {
    id: 'sb-evt-003',
    projectId: 'belmont',
    title: 'Public Open House \u2014 Community Preview',
    date: '2026-03-15',
    time: '11:00 AM \u2013 3:00 PM',
    type: 'open-house',
    location: 'Belmont Showroom, Unit 107',
    attendees: 80,
    notes: 'First public event. Live music, food truck, and hard hat tours.',
  },
  {
    id: 'sb-evt-004',
    projectId: 'belmont',
    title: 'Tenant Meet & Greet \u2014 Signed Lessees',
    date: '2026-03-28',
    time: '6:00 PM \u2013 8:00 PM',
    type: 'private',
    location: 'Belmont Showroom, Unit 107',
    attendees: 20,
    notes: 'Welcome event for signed tenants. TI review and move-in timeline.',
  },
  {
    id: 'sb-evt-005',
    projectId: 'belmont',
    title: 'Neighborhood Association Presentation',
    date: '2026-04-10',
    time: '7:00 PM \u2013 8:30 PM',
    type: 'community',
    location: 'Belmont Community Room (Temporary)',
    attendees: 45,
    notes: 'Traffic study results, landscaping plan, and construction timeline Q&A.',
  },
];

// ─────────────────────────────────────────────
//  POS / Showroom Materials (Belmont only)
// ─────────────────────────────────────────────

export const SEED_POS_ITEMS = [
  {
    id: 'sb-pos-001',
    projectId: 'belmont',
    sku: 'FLR-OAK-001',
    name: 'White Oak Engineered Flooring Sample',
    category: 'Flooring',
    price: 45,
    stock: 30,
    sold: 12,
  },
  {
    id: 'sb-pos-002',
    projectId: 'belmont',
    sku: 'PNT-SW7015',
    name: 'Sherwin-Williams Repose Gray \u2014 Quart Sample',
    category: 'Paint',
    price: 22,
    stock: 50,
    sold: 34,
  },
  {
    id: 'sb-pos-003',
    projectId: 'belmont',
    sku: 'HDW-BRS-010',
    name: 'Brushed Brass Cabinet Pull \u2014 5 in.',
    category: 'Hardware',
    price: 15,
    stock: 48,
    sold: 27,
  },
  {
    id: 'sb-pos-004',
    projectId: 'belmont',
    sku: 'FIX-PLB-020',
    name: 'Kohler Composed Single-Handle Faucet \u2014 Matte Black',
    category: 'Fixtures',
    price: 485,
    stock: 8,
    sold: 3,
  },
  {
    id: 'sb-pos-005',
    projectId: 'belmont',
    sku: 'TLE-PRC-005',
    name: 'Porcelain Subway Tile \u2014 3x12 Warm White',
    category: 'Tile',
    price: 18,
    stock: 40,
    sold: 22,
  },
  {
    id: 'sb-pos-006',
    projectId: 'belmont',
    sku: 'LTG-PND-015',
    name: 'Schoolhouse Electric Pendant \u2014 Brass Dome',
    category: 'Lighting',
    price: 320,
    stock: 5,
    sold: 2,
  },
];

// ─────────────────────────────────────────────
//  Memberships (Belmont only)
// ─────────────────────────────────────────────

export const SEED_MEMBERSHIPS = [
  {
    id: 'sb-mem-001',
    projectId: 'belmont',
    name: 'David Harrington',
    tier: 'vip',
    status: 'active',
    startDate: '2026-01-15',
    endDate: '2027-01-14',
    email: 'dharrington@vanguardwealth.com',
  },
  {
    id: 'sb-mem-002',
    projectId: 'belmont',
    name: 'Sarah Matsuda',
    tier: 'premium',
    status: 'active',
    startDate: '2026-01-20',
    endDate: '2027-01-19',
    email: 'smatsuda@formapilates.com',
  },
  {
    id: 'sb-mem-003',
    projectId: 'belmont',
    name: 'James Ortega',
    tier: 'basic',
    status: 'active',
    startDate: '2026-02-01',
    endDate: '2027-01-31',
    email: 'jortega@boroughbarber.com',
  },
  {
    id: 'sb-mem-004',
    projectId: 'belmont',
    name: 'Linda Chen',
    tier: 'premium',
    status: 'pending',
    startDate: '2026-03-01',
    endDate: '2027-02-28',
    email: 'lchen@groundworkcoffee.com',
  },
  {
    id: 'sb-mem-005',
    projectId: 'belmont',
    name: 'Robert Stein',
    tier: 'vip',
    status: 'pending',
    startDate: '2026-03-01',
    endDate: '2027-02-28',
    email: 'rstein@steinventures.com',
  },
];
