export const SEED_CP_MILESTONES = [
  // ── Belmont — Mixed-Use Development ──
  {
    projectId: 'belmont',
    phase: 'Entitlement',
    startDate: '2025-03-01',
    endDate: '2025-05-31',
    percentComplete: 100,
    status: 'completed',
  },
  {
    projectId: 'belmont',
    phase: 'Precon',
    startDate: '2025-06-01',
    endDate: '2025-08-31',
    percentComplete: 100,
    status: 'completed',
  },
  {
    projectId: 'belmont',
    phase: 'Superstructure',
    startDate: '2025-09-01',
    endDate: '2025-12-20',
    percentComplete: 100,
    status: 'completed',
  },
  {
    projectId: 'belmont',
    phase: 'Rough-ins',
    startDate: '2025-12-21',
    endDate: '2026-03-15',
    percentComplete: 82,
    status: 'at-risk',
  },
  {
    projectId: 'belmont',
    phase: 'Finishes',
    startDate: '2026-03-01',
    endDate: '2026-06-15',
    percentComplete: 12,
    status: 'in-progress',
  },
  {
    projectId: 'belmont',
    phase: 'Closeout',
    startDate: '2026-06-01',
    endDate: '2026-09-30',
    percentComplete: 0,
    status: 'upcoming',
  },

  // ── Wieland — Retail Center ──
  {
    projectId: 'wieland',
    phase: 'Entitlement',
    startDate: '2025-09-01',
    endDate: '2025-12-15',
    percentComplete: 100,
    status: 'completed',
  },
  {
    projectId: 'wieland',
    phase: 'Precon',
    startDate: '2025-12-16',
    endDate: '2026-02-28',
    percentComplete: 65,
    status: 'in-progress',
  },
  {
    projectId: 'wieland',
    phase: 'Superstructure',
    startDate: '2026-03-01',
    endDate: '2026-06-30',
    percentComplete: 0,
    status: 'upcoming',
  },
  {
    projectId: 'wieland',
    phase: 'Rough-ins',
    startDate: '2026-06-01',
    endDate: '2026-08-31',
    percentComplete: 0,
    status: 'upcoming',
  },
  {
    projectId: 'wieland',
    phase: 'Finishes',
    startDate: '2026-08-15',
    endDate: '2026-11-15',
    percentComplete: 0,
    status: 'upcoming',
  },
  {
    projectId: 'wieland',
    phase: 'Closeout',
    startDate: '2026-11-01',
    endDate: '2026-12-31',
    percentComplete: 0,
    status: 'upcoming',
  },

  // ── LaSalle — Office Renovation ──
  {
    projectId: 'lasalle',
    phase: 'Design & Permitting',
    startDate: '2026-01-15',
    endDate: '2026-04-15',
    percentComplete: 40,
    status: 'in-progress',
  },
  {
    projectId: 'lasalle',
    phase: 'Interior Demo',
    startDate: '2026-04-01',
    endDate: '2026-05-15',
    percentComplete: 0,
    status: 'upcoming',
  },
  {
    projectId: 'lasalle',
    phase: 'Fit-Out & Finishes',
    startDate: '2026-05-01',
    endDate: '2026-08-30',
    percentComplete: 0,
    status: 'upcoming',
  },
];

export const SEED_CP_ACTIVITIES = [
  // ══════════════════════════════════════════════════
  // Belmont — Mixed-Use Development
  // ══════════════════════════════════════════════════

  // ── Rough-ins ──
  {
    id: 'CP-RI-01',
    projectId: 'belmont',
    milestonePhase: 'Rough-ins',
    costCode: '23-05',
    trade: 'Mech sub \u2014 AirFlow Mechanical',
    description: 'HVAC ductwork \u2014 supply & return rough-in',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2025-12-21',
    endDate: '2026-02-28',
    percentComplete: 88,
    status: 'in-progress',
    linkedTaskIds: ['RFI-044', 'PCO-011'],
  },
  {
    id: 'CP-RI-02',
    projectId: 'belmont',
    milestonePhase: 'Rough-ins',
    costCode: '26-05',
    trade: 'Elec sub \u2014 Volt Electric',
    description: 'Electrical rough-in \u2014 conduit & wire',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2026-01-05',
    endDate: '2026-03-10',
    percentComplete: 84,
    status: 'in-progress',
    linkedTaskIds: ['PCO-009'],
  },
  {
    id: 'CP-RI-03',
    projectId: 'belmont',
    milestonePhase: 'Rough-ins',
    costCode: '09-21',
    trade: 'Framing sub \u2014 Frame Masters',
    description: 'Drywall & metal framing \u2014 units',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2026-01-10',
    endDate: '2026-03-05',
    percentComplete: 85,
    status: 'in-progress',
    linkedTaskIds: [],
  },
  {
    id: 'CP-RI-04',
    projectId: 'belmont',
    milestonePhase: 'Rough-ins',
    costCode: '22-00',
    trade: 'Plumbing sub \u2014 City Plumbing',
    description: 'Plumbing rough-in \u2014 waste & supply',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2025-12-28',
    endDate: '2026-02-20',
    percentComplete: 92,
    status: 'in-progress',
    linkedTaskIds: [],
  },
  {
    id: 'CP-RI-05',
    projectId: 'belmont',
    milestonePhase: 'Rough-ins',
    costCode: '21-00',
    trade: 'Fire protection sub \u2014 SafeGuard FP',
    description: 'Fire sprinkler rough-in',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2026-01-15',
    endDate: '2026-02-28',
    percentComplete: 75,
    status: 'at-risk',
    linkedTaskIds: ['RFI-047'],
  },
  {
    id: 'CP-RI-06',
    projectId: 'belmont',
    milestonePhase: 'Rough-ins',
    costCode: '23-09',
    trade: 'Controls sub \u2014 BuildSmart Controls',
    description: 'HVAC controls & TAB prep',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-02-15',
    endDate: '2026-03-15',
    percentComplete: 30,
    status: 'in-progress',
    linkedTaskIds: [],
  },
  {
    id: 'CP-RI-07',
    projectId: 'belmont',
    milestonePhase: 'Rough-ins',
    costCode: '07-11',
    trade: 'Waterproofing sub \u2014 AquaShield',
    description: 'Below-grade waterproofing \u2014 final coat',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2026-02-01',
    endDate: '2026-02-20',
    percentComplete: 76,
    status: 'in-progress',
    linkedTaskIds: ['RFI-048'],
  },

  // ── Finishes ──
  {
    id: 'CP-FI-01',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '09-31',
    trade: 'Tile sub \u2014 Premier Tile',
    description: 'Porcelain tile \u2014 bathrooms',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-03-10',
    endDate: '2026-04-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['RFI-047', 'DEC-005', 'LT-005'],
  },
  {
    id: 'CP-FI-02',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '09-65',
    trade: 'Flooring sub \u2014 FloorCraft',
    description: 'Resilient flooring \u2014 LVP common areas',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-03-15',
    endDate: '2026-05-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['DEC-006'],
  },
  {
    id: 'CP-FI-03',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '09-91',
    trade: 'Painting sub \u2014 ColorPro',
    description: 'Painting \u2014 interior units',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2026-03-20',
    endDate: '2026-05-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
  {
    id: 'CP-FI-04',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '06-20',
    trade: 'Millwork sub \u2014 Custom Craft',
    description: 'Custom cabinetry \u2014 lobby & amenity',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-04-01',
    endDate: '2026-05-20',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['SUB-013'],
  },
  {
    id: 'CP-FI-05',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '09-32',
    trade: 'Stone sub \u2014 Natural Stone Works',
    description: 'Natural stone \u2014 lobby feature wall',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-04-15',
    endDate: '2026-05-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['DEC-005'],
  },
  {
    id: 'CP-FI-06',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '26-51',
    trade: 'Elec sub \u2014 Volt Electric',
    description: 'Lighting fixtures \u2014 install & trim',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2026-04-01',
    endDate: '2026-06-01',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['SUB-011'],
  },
  {
    id: 'CP-FI-07',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '32-12',
    trade: 'Hardscape sub \u2014 Metro Paving',
    description: 'Hardscape \u2014 pavers & curbing',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-04-15',
    endDate: '2026-06-01',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
  {
    id: 'CP-FI-08',
    projectId: 'belmont',
    milestonePhase: 'Finishes',
    costCode: '32-90',
    trade: 'Landscape sub \u2014 GreenScape',
    description: 'Planting & irrigation',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-05-01',
    endDate: '2026-06-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },

  // ── Closeout ──
  {
    id: 'CP-CO-01',
    projectId: 'belmont',
    milestonePhase: 'Closeout',
    costCode: 'GEN',
    trade: 'GC \u2014 SHB Inc.',
    description: 'Punch list \u2014 all trades',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-06-01',
    endDate: '2026-07-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
  {
    id: 'CP-CO-02',
    projectId: 'belmont',
    milestonePhase: 'Closeout',
    costCode: '14-00',
    trade: 'Elevator sub \u2014 ThyssenKrupp',
    description: 'Elevator testing & final inspection',
    owner: 'Mike S.',
    role: 'Super',
    startDate: '2026-06-15',
    endDate: '2026-07-31',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['SUB-011', 'LT-012'],
  },
  {
    id: 'CP-CO-03',
    projectId: 'belmont',
    milestonePhase: 'Closeout',
    costCode: '23-00',
    trade: 'Controls sub \u2014 BuildSmart Controls',
    description: 'TAB & commissioning \u2014 HVAC systems',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-06-01',
    endDate: '2026-07-31',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['WC-001'],
  },
  {
    id: 'CP-CO-04',
    projectId: 'belmont',
    milestonePhase: 'Closeout',
    costCode: 'GEN',
    trade: 'GC \u2014 SHB Inc.',
    description: 'O&M manuals & warranty handoff',
    owner: 'Taylor R.',
    role: 'Ops',
    startDate: '2026-07-15',
    endDate: '2026-09-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['WC-003'],
  },
  {
    id: 'CP-CO-05',
    projectId: 'belmont',
    milestonePhase: 'Closeout',
    costCode: 'GEN',
    trade: 'GC \u2014 SHB Inc.',
    description: 'Final lien releases & close-out docs',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['PA-005'],
  },

  // ══════════════════════════════════════════════════
  // Wieland — Retail Center
  // ══════════════════════════════════════════════════

  // ── Precon ──
  {
    id: 'GF-CP-PC-01',
    projectId: 'wieland',
    milestonePhase: 'Precon',
    costCode: '31-23',
    trade: 'Earthwork sub \u2014 Valley Grading Co.',
    description: 'Mass grading & soil export',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-01-05',
    endDate: '2026-02-28',
    percentComplete: 55,
    status: 'at-risk',
    linkedTaskIds: ['GF-PCO-001', 'GF-INV-001'],
  },
  {
    id: 'GF-CP-PC-02',
    projectId: 'wieland',
    milestonePhase: 'Precon',
    costCode: '31-25',
    trade: 'Earthwork sub \u2014 Valley Grading Co.',
    description: 'Structural fill import & compaction',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-02-01',
    endDate: '2026-03-10',
    percentComplete: 50,
    status: 'in-progress',
    linkedTaskIds: [],
  },
  {
    id: 'GF-CP-PC-03',
    projectId: 'wieland',
    milestonePhase: 'Precon',
    costCode: '03-10',
    trade: 'Concrete sub \u2014 Atlas Concrete',
    description: 'Spread footings & piers',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-02-15',
    endDate: '2026-04-01',
    percentComplete: 20,
    status: 'in-progress',
    linkedTaskIds: [],
  },
  {
    id: 'GF-CP-PC-04',
    projectId: 'wieland',
    milestonePhase: 'Precon',
    costCode: 'GEN',
    trade: 'GC \u2014 SHB Inc.',
    description: 'Bid package prep \u2014 steel & envelope',
    owner: 'Dana W.',
    role: 'Procurement',
    startDate: '2026-01-15',
    endDate: '2026-02-15',
    percentComplete: 80,
    status: 'in-progress',
    linkedTaskIds: ['GF-SUB-001'],
  },

  // ── Superstructure ──
  {
    id: 'GF-CP-SS-01',
    projectId: 'wieland',
    milestonePhase: 'Superstructure',
    costCode: '05-12',
    trade: 'Steel sub \u2014 Ironworks Fabrication',
    description: 'Structural steel \u2014 fabrication & erection',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-04-10',
    endDate: '2026-06-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['GF-SUB-001', 'GF-LT-001'],
  },
  {
    id: 'GF-CP-SS-02',
    projectId: 'wieland',
    milestonePhase: 'Superstructure',
    costCode: '05-50',
    trade: 'Steel sub \u2014 Ironworks Fabrication',
    description: 'Metal decking',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
  {
    id: 'GF-CP-SS-03',
    projectId: 'wieland',
    milestonePhase: 'Superstructure',
    costCode: '08-44',
    trade: 'Glazing sub \u2014 ClearView Glazing',
    description: 'Storefront curtain wall system',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-05-15',
    endDate: '2026-06-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['GF-RFI-001'],
  },

  // ── Rough-ins ──
  {
    id: 'GF-CP-RI-01',
    projectId: 'wieland',
    milestonePhase: 'Rough-ins',
    costCode: '23-00',
    trade: 'Mech sub \u2014 TBD',
    description: 'HVAC rough-in \u2014 retail units',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-06-15',
    endDate: '2026-08-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
  {
    id: 'GF-CP-RI-02',
    projectId: 'wieland',
    milestonePhase: 'Rough-ins',
    costCode: '26-00',
    trade: 'Elec sub \u2014 TBD',
    description: 'Electrical rough-in \u2014 retail & site',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-06-15',
    endDate: '2026-08-31',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },

  // ── Finishes ──
  {
    id: 'GF-CP-FI-01',
    projectId: 'wieland',
    milestonePhase: 'Finishes',
    costCode: '32-12',
    trade: 'Paving sub \u2014 TBD',
    description: 'Parking lot paving',
    owner: 'Dana W.',
    role: 'Procurement',
    startDate: '2026-09-01',
    endDate: '2026-10-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: ['GF-DEC-001'],
  },
  {
    id: 'GF-CP-FI-02',
    projectId: 'wieland',
    milestonePhase: 'Finishes',
    costCode: '32-90',
    trade: 'Landscape sub \u2014 TBD',
    description: 'Landscape & irrigation',
    owner: 'Dana W.',
    role: 'Procurement',
    startDate: '2026-10-01',
    endDate: '2026-11-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
  {
    id: 'GF-CP-FI-03',
    projectId: 'wieland',
    milestonePhase: 'Finishes',
    costCode: '08-80',
    trade: 'Glazing sub \u2014 ClearView Glazing',
    description: 'Glazing \u2014 insulated units',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-09-01',
    endDate: '2026-10-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },

  // ── Closeout ──
  {
    id: 'GF-CP-CO-01',
    projectId: 'wieland',
    milestonePhase: 'Closeout',
    costCode: 'GEN',
    trade: 'GC \u2014 SHB Inc.',
    description: 'Punch list & final inspections',
    owner: 'Chris L.',
    role: 'PM',
    startDate: '2026-11-01',
    endDate: '2026-12-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
  {
    id: 'GF-CP-CO-02',
    projectId: 'wieland',
    milestonePhase: 'Closeout',
    costCode: 'GEN',
    trade: 'GC \u2014 SHB Inc.',
    description: 'Tenant turnover & close-out docs',
    owner: 'Dana W.',
    role: 'Procurement',
    startDate: '2026-12-01',
    endDate: '2026-12-31',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },

  // ══════════════════════════════════════════════════
  // LaSalle — Office Renovation
  // ══════════════════════════════════════════════════

  // ── Design & Permitting ──
  {
    id: 'LS-CP-DP-01',
    projectId: 'lasalle',
    milestonePhase: 'Design & Permitting',
    costCode: 'GEN',
    trade: 'GC \u2014 SHB Inc.',
    description: 'Existing conditions survey & as-builts',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-01-15',
    endDate: '2026-02-15',
    percentComplete: 90,
    status: 'in-progress',
    linkedTaskIds: [],
  },
  {
    id: 'LS-CP-DP-02',
    projectId: 'lasalle',
    milestonePhase: 'Design & Permitting',
    costCode: 'GEN',
    trade: 'Design \u2014 SHB Studio',
    description: 'Construction documents & permit submission',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-02-01',
    endDate: '2026-04-15',
    percentComplete: 35,
    status: 'in-progress',
    linkedTaskIds: [],
  },

  // ── Interior Demo ──
  {
    id: 'LS-CP-ID-01',
    projectId: 'lasalle',
    milestonePhase: 'Interior Demo',
    costCode: '02-41',
    trade: 'Demo sub \u2014 Metro Demo Co.',
    description: 'Interior selective demolition',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-04-01',
    endDate: '2026-05-15',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },

  // ── Fit-Out & Finishes ──
  {
    id: 'LS-CP-FO-01',
    projectId: 'lasalle',
    milestonePhase: 'Fit-Out & Finishes',
    costCode: '09-21',
    trade: 'Framing sub \u2014 TBD',
    description: 'Interior framing & drywall',
    owner: 'Jordan M.',
    role: 'PM',
    startDate: '2026-05-01',
    endDate: '2026-08-30',
    percentComplete: 0,
    status: 'upcoming',
    linkedTaskIds: [],
  },
];
