export const SEED_QUALITY_BY_TYPE = [
  // ── Belmont — Mixed-Use Development ──
  {
    projectId: 'belmont',
    type: 'Drawing',
    total: 94,
    current: 86,
    pendingReview: 3,
    revisionNeeded: 2,
    affectedByOpenTask: 3,
  },
  {
    projectId: 'belmont',
    type: 'Spec',
    total: 38,
    current: 36,
    pendingReview: 1,
    revisionNeeded: 0,
    affectedByOpenTask: 1,
  },
  {
    projectId: 'belmont',
    type: 'Submittal',
    total: 32,
    current: 28,
    pendingReview: 2,
    revisionNeeded: 0,
    affectedByOpenTask: 2,
  },
  {
    projectId: 'belmont',
    type: 'QC',
    total: 22,
    current: 20,
    pendingReview: 0,
    revisionNeeded: 0,
    affectedByOpenTask: 2,
  },

  // ── Wieland — Retail Center ──
  {
    projectId: 'wieland',
    type: 'Drawing',
    total: 32,
    current: 28,
    pendingReview: 2,
    revisionNeeded: 1,
    affectedByOpenTask: 1,
  },
  {
    projectId: 'wieland',
    type: 'Spec',
    total: 14,
    current: 12,
    pendingReview: 1,
    revisionNeeded: 0,
    affectedByOpenTask: 1,
  },
  {
    projectId: 'wieland',
    type: 'Submittal',
    total: 12,
    current: 11,
    pendingReview: 0,
    revisionNeeded: 0,
    affectedByOpenTask: 1,
  },
  {
    projectId: 'wieland',
    type: 'QC',
    total: 6,
    current: 6,
    pendingReview: 0,
    revisionNeeded: 0,
    affectedByOpenTask: 0,
  },

  // ── LaSalle — Office Renovation ──
  {
    projectId: 'lasalle',
    type: 'Drawing',
    total: 18,
    current: 16,
    pendingReview: 1,
    revisionNeeded: 1,
    affectedByOpenTask: 0,
  },
  {
    projectId: 'lasalle',
    type: 'Spec',
    total: 8,
    current: 8,
    pendingReview: 0,
    revisionNeeded: 0,
    affectedByOpenTask: 0,
  },
  {
    projectId: 'lasalle',
    type: 'Submittal',
    total: 4,
    current: 3,
    pendingReview: 1,
    revisionNeeded: 0,
    affectedByOpenTask: 0,
  },
  {
    projectId: 'lasalle',
    type: 'QC',
    total: 2,
    current: 2,
    pendingReview: 0,
    revisionNeeded: 0,
    affectedByOpenTask: 0,
  },
];
