export const SEED_SCHEDULE_PHASES = [
  // ── Belmont — Mixed-Use Development ──
  {
    id: 'PH-01',
    projectId: 'belmont',
    name: 'Foundation & Earthwork',
    startDate: '2025-06-01',
    endDate: '2025-09-15',
    percentComplete: 100,
    plannedPercent: 100,
    daysVariance: 0,
    linkedTaskIds: [],
    potentialImpactDays: 0,
  },
  {
    id: 'PH-02',
    projectId: 'belmont',
    name: 'Structure & Concrete',
    startDate: '2025-09-16',
    endDate: '2025-12-20',
    percentComplete: 100,
    plannedPercent: 100,
    daysVariance: 0,
    linkedTaskIds: [],
    potentialImpactDays: 0,
  },
  {
    id: 'PH-03',
    projectId: 'belmont',
    name: 'Rough-In (MEP + Framing)',
    startDate: '2025-12-21',
    endDate: '2026-03-15',
    percentComplete: 82,
    plannedPercent: 85,
    daysVariance: -3,
    linkedTaskIds: ['RFI-044', 'RFI-047', 'PCO-009', 'PCO-011', 'PT-014'],
    potentialImpactDays: 4,
  },
  {
    id: 'PH-04',
    projectId: 'belmont',
    name: 'Finishes & Interiors',
    startDate: '2026-03-01',
    endDate: '2026-06-15',
    percentComplete: 12,
    plannedPercent: 15,
    daysVariance: -2,
    linkedTaskIds: ['DEC-005', 'DEC-006', 'SUB-011', 'SUB-013', 'LT-005'],
    potentialImpactDays: 8,
  },
  {
    id: 'PH-05',
    projectId: 'belmont',
    name: 'Systems Testing & Commissioning',
    startDate: '2026-06-01',
    endDate: '2026-07-31',
    percentComplete: 0,
    plannedPercent: 0,
    daysVariance: 0,
    linkedTaskIds: [],
    potentialImpactDays: 0,
  },
  {
    id: 'PH-06',
    projectId: 'belmont',
    name: 'Turnover & Warranty',
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    percentComplete: 0,
    plannedPercent: 0,
    daysVariance: 0,
    linkedTaskIds: ['WC-001', 'WC-003'],
    potentialImpactDays: 0,
  },

  // ── Wieland — Retail Center ──
  {
    id: 'GF-PH-01',
    projectId: 'wieland',
    name: 'Site Work & Grading',
    startDate: '2026-01-05',
    endDate: '2026-03-15',
    percentComplete: 55,
    plannedPercent: 60,
    daysVariance: -3,
    linkedTaskIds: ['GF-PCO-001'],
    potentialImpactDays: 3,
  },
  {
    id: 'GF-PH-02',
    projectId: 'wieland',
    name: 'Foundations & Slab',
    startDate: '2026-03-01',
    endDate: '2026-05-15',
    percentComplete: 0,
    plannedPercent: 0,
    daysVariance: 0,
    linkedTaskIds: [],
    potentialImpactDays: 0,
  },
  {
    id: 'GF-PH-03',
    projectId: 'wieland',
    name: 'Structure & Envelope',
    startDate: '2026-05-01',
    endDate: '2026-08-30',
    percentComplete: 0,
    plannedPercent: 0,
    daysVariance: 0,
    linkedTaskIds: ['GF-RFI-001', 'GF-SUB-001', 'GF-LT-001'],
    potentialImpactDays: 2,
  },
  {
    id: 'GF-PH-04',
    projectId: 'wieland',
    name: 'Finishes & Turnover',
    startDate: '2026-08-15',
    endDate: '2026-11-30',
    percentComplete: 0,
    plannedPercent: 0,
    daysVariance: 0,
    linkedTaskIds: ['GF-DEC-001'],
    potentialImpactDays: 0,
  },

  // ── LaSalle — Office Renovation ──
  {
    id: 'LS-PH-01',
    projectId: 'lasalle',
    name: 'Design & Permitting',
    startDate: '2026-01-15',
    endDate: '2026-04-15',
    percentComplete: 40,
    plannedPercent: 45,
    daysVariance: -2,
    linkedTaskIds: [],
    potentialImpactDays: 0,
  },
  {
    id: 'LS-PH-02',
    projectId: 'lasalle',
    name: 'Interior Demo',
    startDate: '2026-04-01',
    endDate: '2026-05-15',
    percentComplete: 0,
    plannedPercent: 0,
    daysVariance: 0,
    linkedTaskIds: [],
    potentialImpactDays: 0,
  },
  {
    id: 'LS-PH-03',
    projectId: 'lasalle',
    name: 'Fit-Out & Finishes',
    startDate: '2026-05-01',
    endDate: '2026-08-30',
    percentComplete: 0,
    plannedPercent: 0,
    daysVariance: 0,
    linkedTaskIds: [],
    potentialImpactDays: 0,
  },
];
