/**
 * Seed tasks — ported from dashboard mock data.
 *
 * Project ID mapping:
 *   sandbox-001   -> belmont
 *   greenfield-002 -> wieland
 *   (new)          -> lasalle
 *
 * All dates are ISO strings. All monetary values are numbers.
 */

export const SEED_TASKS = [
  // ════════════════════════════════════════════════
  // BELMONT — Mixed-Use Development (23 tasks)
  // ════════════════════════════════════════════════

  // ── RFIs ──
  {
    id: 'RFI-047',
    projectId: 'belmont',
    category: 'RFI',
    subject: 'Tile layout vs reflected ceiling conflict',
    owner: 'Taylor R.',
    urgency: 'overdue',
    daysOverdue: 5,
    slaDate: '2026-02-03',
    createdDate: '2026-01-27',
    source: 'Fieldwire clash report',
    deepLinks: [
      { target: 'Smartsheet', label: 'RFI Log #047', url: '#smartsheet-rfi-047' },
      { target: 'Slack', label: '#rfi-queue', url: '#slack-rfi-queue' },
      { target: 'Fieldwire', label: 'Clash Report', url: '#fieldwire-clash-047' },
    ],
    detail: {
      type: 'RFI',
      rfiNumber: 'RFI-047',
      discipline: 'Architectural / MEP',
      questionSummary: 'Tile layout pattern on Level 2 corridor conflicts with reflected ceiling grid. Which takes priority?',
      designContact: 'SHB Studio — Design Lead',
      submittedDate: '2026-01-27',
      responseDeadline: '2026-02-03',
      impactedAreas: ['Level 2 Corridor', 'Ceiling Grid'],
      linkedSubmittals: ['SUB-011'],
    },
    relatedTaskIds: ['SUB-011'],
    scheduleImpactDays: 2,
    qualityAffected: ['Drawing-A201', 'Drawing-M102'],
    costCodeRef: '09-30',
    attachments: [],
  },
  {
    id: 'RFI-044',
    projectId: 'belmont',
    category: 'RFI',
    subject: 'Mechanical chase routing conflict Level 3',
    owner: 'Taylor R.',
    urgency: 'overdue',
    daysOverdue: 3,
    slaDate: '2026-02-05',
    createdDate: '2026-01-29',
    source: 'Site inspection',
    deepLinks: [
      { target: 'Smartsheet', label: 'RFI Log #044', url: '#smartsheet-rfi-044' },
      { target: 'Slack', label: '#rfi-queue', url: '#slack-rfi-queue' },
      { target: 'Doc', label: 'Site Photo', url: '#doc-site-photo-044' },
    ],
    detail: {
      type: 'RFI',
      rfiNumber: 'RFI-044',
      discipline: 'Mechanical',
      questionSummary: 'Mechanical chase on Level 3 conflicts with structural beam. Need alternate routing or beam modification.',
      designContact: 'SHB Studio — Mechanical Engineer',
      submittedDate: '2026-01-29',
      responseDeadline: '2026-02-05',
      impactedAreas: ['Level 3 Mechanical Chase', 'Structural Grid C-4'],
      linkedSubmittals: [],
    },
    relatedTaskIds: ['PCO-011'],
    costImpact: 12000,
    scheduleImpactDays: 3,
    qualityAffected: ['Drawing-M301'],
    costCodeRef: '23-00',
    attachments: [],
  },
  {
    id: 'RFI-048',
    projectId: 'belmont',
    category: 'RFI',
    subject: 'Waterproofing detail at planter wall',
    owner: 'Taylor R.',
    urgency: 'new',
    slaDate: '2026-02-14',
    createdDate: '2026-02-07',
    source: 'Design review',
    deepLinks: [
      { target: 'Smartsheet', label: 'RFI Log #048', url: '#smartsheet-rfi-048' },
      { target: 'Doc', label: 'Detail Drawing', url: '#doc-waterproof-048' },
    ],
    detail: {
      type: 'RFI',
      rfiNumber: 'RFI-048',
      discipline: 'Architectural',
      questionSummary: 'Waterproofing membrane detail at roof terrace planter wall not shown on drawings. Need spec and detail.',
      designContact: 'SHB Studio — Architect',
      submittedDate: '2026-02-07',
      responseDeadline: '2026-02-14',
      impactedAreas: ['Roof Terrace', 'Planter Walls'],
    },
    relatedTaskIds: [],
    qualityAffected: ['Drawing-A501'],
    costCodeRef: '07-00',
    attachments: [
      { type: 'drawing', label: 'Waterproofing detail sketch', url: '#doc-waterproof-sketch-048' },
    ],
  },

  // ── Change Orders ──
  {
    id: 'PCO-009',
    projectId: 'belmont',
    category: 'CO',
    subject: 'Electrical panel relocation Level 2',
    owner: 'Jordan M.',
    urgency: 'overdue',
    daysOverdue: 2,
    slaDate: '2026-02-06',
    createdDate: '2026-01-30',
    source: 'RFI-041 resolution',
    deepLinks: [
      { target: 'Smartsheet', label: 'CO Log #009', url: '#smartsheet-pco-009' },
      { target: 'Slack', label: '#change-orders', url: '#slack-co' },
      { target: 'Sheet', label: 'Cost Estimate', url: '#sheet-pco-009' },
    ],
    detail: {
      type: 'CO',
      pcoNumber: 'PCO-009',
      estimatedCost: 34200,
      costCode: '26-00 Electrical',
      reason: 'Panel relocation required due to mechanical chase conflict resolved in RFI-041',
      submittedBy: 'Electrical Sub — Spark Electric',
      approvalChain: ['Jordan M.', 'Sam W.'],
      linkedRfis: ['RFI-041'],
    },
    relatedTaskIds: [],
    costImpact: 34200,
    scheduleImpactDays: 1,
    qualityAffected: [],
    costCodeRef: '26-00',
    attachments: [
      { type: 'contract', label: 'PCO-009 cost estimate', url: '#doc-pco-009-estimate' },
      { type: 'drawing', label: 'Panel relocation plan', url: '#dwg-panel-reloc' },
    ],
  },
  {
    id: 'PCO-011',
    projectId: 'belmont',
    category: 'CO',
    subject: 'Mechanical reroute Level 3',
    owner: 'Jordan M.',
    urgency: 'watching',
    daysUntilDue: 8,
    slaDate: '2026-02-16',
    createdDate: '2026-02-01',
    source: 'RFI-044 pending',
    deepLinks: [
      { target: 'Smartsheet', label: 'CO Log #011', url: '#smartsheet-pco-011' },
      { target: 'Slack', label: '#change-orders', url: '#slack-co' },
    ],
    detail: {
      type: 'CO',
      pcoNumber: 'PCO-011',
      estimatedCost: 18400,
      costCode: '23-00 HVAC',
      reason: 'Potential mechanical reroute pending RFI-044 response',
      submittedBy: 'Crown Mechanical',
      approvalChain: ['Jordan M.', 'Sam W.'],
      linkedRfis: ['RFI-044'],
    },
    relatedTaskIds: ['RFI-044'],
    costImpact: 18400,
    scheduleImpactDays: 2,
    qualityAffected: [],
    costCodeRef: '23-00',
    attachments: [],
  },

  // ── Invoices ──
  {
    id: 'INV-8834',
    projectId: 'belmont',
    category: 'Invoice',
    subject: 'Electrical rough-in billing',
    owner: 'Jordan M.',
    urgency: 'due-today',
    slaDate: '2026-02-08',
    createdDate: '2026-02-03',
    source: 'Email — Spark Electric',
    deepLinks: [
      { target: 'Sheet', label: 'Invoice Sheet', url: '#sheet-inv-8834' },
      { target: 'Email', label: 'Original Email', url: '#email-inv-8834' },
      { target: 'Adaptive', label: 'Cost Code', url: '#adaptive-26-00' },
    ],
    detail: {
      type: 'Invoice',
      invoiceNumber: 'INV-8834',
      vendor: 'Spark Electric',
      amount: 47800,
      costCode: '26-00 Electrical',
      submittedDate: '2026-02-03',
      issue: 'Line item 3 exceeds approved SOV by $4,200. Needs verification.',
      matchStatus: 'partial',
    },
    relatedTaskIds: [],
    costImpact: 47800,
    scheduleImpactDays: null,
    qualityAffected: [],
    costCodeRef: '26-00',
    attachments: [
      { type: 'contract', label: 'Invoice INV-8834.pdf', url: '#pdf-inv-8834' },
      { type: 'spec', label: 'SOV backup — Electrical', url: '#doc-sov-elec' },
    ],
  },
  {
    id: 'INV-CM-2267',
    projectId: 'belmont',
    category: 'Invoice',
    subject: 'Crown Mechanical CO work (missing job #)',
    owner: 'Jordan M.',
    urgency: 'due-today',
    slaDate: '2026-02-08',
    createdDate: '2026-02-04',
    source: 'Email — Crown Mechanical',
    deepLinks: [
      { target: 'Sheet', label: 'Invoice Sheet', url: '#sheet-inv-cm-2267' },
      { target: 'Email', label: 'Original Email', url: '#email-inv-cm-2267' },
    ],
    detail: {
      type: 'Invoice',
      invoiceNumber: 'INV-CM-2267',
      vendor: 'Crown Mechanical',
      amount: 22100,
      costCode: '23-00 HVAC',
      submittedDate: '2026-02-04',
      issue: 'Missing job number. Cannot match to approved CO. Need vendor to resubmit.',
      matchStatus: 'unmatched',
    },
    relatedTaskIds: [],
    costImpact: 22100,
    scheduleImpactDays: null,
    qualityAffected: [],
    costCodeRef: '23-00',
    attachments: [
      { type: 'contract', label: 'Invoice INV-CM-2267.pdf', url: '#pdf-inv-cm-2267' },
    ],
  },

  // ── Decisions ──
  {
    id: 'DEC-005',
    projectId: 'belmont',
    category: 'Decision',
    subject: 'Lobby finish material substitution',
    owner: 'Rachel K.',
    urgency: 'overdue',
    daysOverdue: 4,
    slaDate: '2026-02-04',
    createdDate: '2026-01-28',
    source: 'Design meeting',
    deepLinks: [
      { target: 'Smartsheet', label: 'Decision Log #005', url: '#smartsheet-dec-005' },
      { target: 'Slack', label: '#decisions', url: '#slack-decisions' },
      { target: 'Doc', label: 'Material Options', url: '#doc-material-options' },
    ],
    detail: {
      type: 'Decision',
      decisionNumber: 'DEC-005',
      requestedBy: 'SHB Studio — Interior Designer',
      options: ['Option A: Italian marble (as spec)', 'Option B: Domestic granite (cost saving)', 'Option C: Porcelain large-format tile (lead time saving)'],
      deadline: '2026-02-04',
      impact: 'Affects lobby stone cladding procurement (LT-005) and finish schedule',
      stakeholders: ['Rachel K.', 'Sam W.', 'Alex P.'],
    },
    relatedTaskIds: ['LT-005'],
    costImpact: -15000,
    scheduleImpactDays: 4,
    qualityAffected: [],
    costCodeRef: '09-30',
    attachments: [
      { type: 'spec', label: 'Material comparison matrix', url: '#doc-material-comparison' },
      { type: 'photo', label: 'Finish samples gallery', url: '#photo-finish-samples' },
    ],
  },
  {
    id: 'DEC-006',
    projectId: 'belmont',
    category: 'Decision',
    subject: 'Roof terrace railing design change',
    owner: 'Sam W.',
    urgency: 'new',
    slaDate: '2026-02-15',
    createdDate: '2026-02-06',
    source: 'Principal review',
    deepLinks: [
      { target: 'Smartsheet', label: 'Decision Log #006', url: '#smartsheet-dec-006' },
      { target: 'Doc', label: 'Design Sketches', url: '#doc-railing-sketches' },
    ],
    detail: {
      type: 'Decision',
      decisionNumber: 'DEC-006',
      requestedBy: 'Sam W. — Principal',
      options: ['Option A: Cable railing (as designed)', 'Option B: Glass panel railing (upgraded)'],
      deadline: '2026-02-15',
      impact: 'Potential $8K cost increase if glass panel selected. No schedule impact.',
      stakeholders: ['Sam W.', 'Rachel K.'],
    },
    relatedTaskIds: [],
    costImpact: 8000,
    scheduleImpactDays: null,
    qualityAffected: [],
    costCodeRef: '09-00',
    attachments: [
      { type: 'drawing', label: 'Railing design sketches', url: '#doc-railing-sketch' },
    ],
  },

  // ── Submittals ──
  {
    id: 'SUB-011',
    projectId: 'belmont',
    category: 'Submittal',
    subject: 'Elevator cab finish samples',
    owner: 'Taylor R.',
    urgency: 'overdue',
    daysOverdue: 6,
    slaDate: '2026-02-02',
    createdDate: '2026-01-20',
    source: 'Submittal log',
    deepLinks: [
      { target: 'Smartsheet', label: 'Submittal Log #011', url: '#smartsheet-sub-011' },
      { target: 'Slack', label: '#submittals', url: '#slack-submittals' },
    ],
    detail: {
      type: 'Submittal',
      submittalNumber: 'SUB-011',
      specSection: '14 20 00 — Elevators',
      vendor: 'Pacific Elevator Co.',
      submittedDate: '2026-01-20',
      reviewDeadline: '2026-02-02',
      revisionNumber: 1,
      reviewers: ['Taylor R.', 'SHB Studio'],
    },
    relatedTaskIds: ['LT-012'],
    scheduleImpactDays: 3,
    qualityAffected: ['Submittal-014'],
    costCodeRef: '14-00',
    attachments: [
      { type: 'spec', label: 'Cab finish spec 14 20 00', url: '#doc-cab-spec' },
      { type: 'photo', label: 'Sample photos — Rev 1', url: '#photo-cab-samples' },
    ],
  },
  {
    id: 'SUB-013',
    projectId: 'belmont',
    category: 'Submittal',
    subject: 'Custom millwork shop drawings',
    owner: 'Taylor R.',
    urgency: 'new',
    slaDate: '2026-02-18',
    createdDate: '2026-02-06',
    source: 'Vendor submission',
    deepLinks: [
      { target: 'Smartsheet', label: 'Submittal Log #013', url: '#smartsheet-sub-013' },
      { target: 'Doc', label: 'Shop Drawings', url: '#doc-millwork-013' },
    ],
    detail: {
      type: 'Submittal',
      submittalNumber: 'SUB-013',
      specSection: '06 40 00 — Architectural Woodwork',
      vendor: 'Heritage Millwork',
      submittedDate: '2026-02-06',
      reviewDeadline: '2026-02-18',
      revisionNumber: 0,
      reviewers: ['Taylor R.', 'SHB Studio'],
    },
    relatedTaskIds: [],
    qualityAffected: ['Submittal-016'],
    costCodeRef: '06-00',
    attachments: [
      { type: 'drawing', label: 'Millwork shop drawings.pdf', url: '#pdf-millwork-shop-dwg' },
      { type: 'spec', label: 'Spec 06 40 00 — Woodwork', url: '#doc-spec-0640' },
    ],
  },

  // ── Lead Times ──
  {
    id: 'LT-005',
    projectId: 'belmont',
    category: 'Lead Time',
    subject: 'Lobby stone cladding (CRITICAL -8d)',
    owner: 'Alex P.',
    urgency: 'overdue',
    daysOverdue: 8,
    slaDate: '2026-01-31',
    createdDate: '2026-01-15',
    source: 'Procurement tracker',
    deepLinks: [
      { target: 'Smartsheet', label: 'Procurement Log', url: '#smartsheet-lt-005' },
      { target: 'Slack', label: '#procurement', url: '#slack-procurement' },
    ],
    detail: {
      type: 'Lead Time',
      itemDescription: 'Italian marble lobby stone cladding — 420 SF',
      vendor: 'Mediterranean Stone Imports',
      orderDate: '2026-01-10',
      expectedDelivery: '2026-03-15',
      requiredOnSite: '2026-03-07',
      floatDays: -8,
      riskLevel: 'critical',
    },
    relatedTaskIds: ['DEC-005'],
    costImpact: 0,
    scheduleImpactDays: 8,
    qualityAffected: [],
    costCodeRef: '09-30',
    attachments: [
      { type: 'spec', label: 'Stone spec — Italian marble', url: '#doc-marble-spec' },
      { type: 'contract', label: 'PO — Mediterranean Stone', url: '#doc-po-med-stone' },
    ],
  },
  {
    id: 'LT-008',
    projectId: 'belmont',
    category: 'Lead Time',
    subject: 'Lobby pendant fixtures (AT-RISK 4d)',
    owner: 'Alex P.',
    urgency: 'watching',
    daysUntilDue: 4,
    slaDate: '2026-02-12',
    createdDate: '2026-01-20',
    source: 'Procurement tracker',
    deepLinks: [
      { target: 'Smartsheet', label: 'Procurement Log', url: '#smartsheet-lt-008' },
    ],
    detail: {
      type: 'Lead Time',
      itemDescription: 'Custom pendant light fixtures — lobby and corridors (qty 12)',
      vendor: 'Luminary Design Co.',
      orderDate: '2026-01-15',
      expectedDelivery: '2026-03-20',
      requiredOnSite: '2026-03-24',
      floatDays: 4,
      riskLevel: 'at-risk',
    },
    relatedTaskIds: [],
    scheduleImpactDays: 0,
    qualityAffected: [],
    costCodeRef: '26-00',
    attachments: [
      { type: 'spec', label: 'Fixture cut sheets — pendants', url: '#doc-pendant-cutsheet' },
    ],
  },
  {
    id: 'LT-012',
    projectId: 'belmont',
    category: 'Lead Time',
    subject: 'Elevator cab panels (18d float)',
    owner: 'Alex P.',
    urgency: 'watching',
    daysUntilDue: 18,
    slaDate: '2026-02-26',
    createdDate: '2026-01-25',
    source: 'Procurement tracker',
    deepLinks: [
      { target: 'Smartsheet', label: 'Procurement Log', url: '#smartsheet-lt-012' },
    ],
    detail: {
      type: 'Lead Time',
      itemDescription: 'Elevator cab interior panels — custom laminate finish',
      vendor: 'Pacific Elevator Co.',
      orderDate: '2026-01-20',
      expectedDelivery: '2026-04-01',
      requiredOnSite: '2026-04-19',
      floatDays: 18,
      riskLevel: 'on-track',
    },
    relatedTaskIds: ['SUB-011'],
    scheduleImpactDays: 0,
    qualityAffected: [],
    costCodeRef: '14-00',
    attachments: [
      { type: 'spec', label: 'Laminate finish samples', url: '#doc-laminate-samples' },
    ],
  },

  // ── Warranty ──
  {
    id: 'WC-001',
    projectId: 'belmont',
    category: 'Warranty',
    subject: 'Unit 204 HVAC noise complaint',
    owner: 'Jordan M.',
    urgency: 'overdue',
    daysOverdue: 6,
    slaDate: '2026-02-02',
    createdDate: '2026-01-25',
    source: 'Tenant complaint email',
    deepLinks: [
      { target: 'Sheet', label: 'Warranty Log', url: '#sheet-wc-001' },
      { target: 'Email', label: 'Complaint', url: '#email-wc-001' },
      { target: 'CompanyCam', label: 'Site Photos', url: '#companycam-wc-001' },
    ],
    detail: {
      type: 'Warranty',
      claimNumber: 'WC-001',
      unit: 'Unit 204',
      issueType: 'HVAC — Excessive noise from fan coil unit',
      reportedDate: '2026-01-25',
      severity: 'urgent',
      assignedTo: 'Crown Mechanical',
    },
    relatedTaskIds: [],
    qualityAffected: [],
    costCodeRef: null,
    attachments: [],
  },
  {
    id: 'WC-003',
    projectId: 'belmont',
    category: 'Warranty',
    subject: 'Unit 308 water stain (possible leak)',
    owner: 'Jordan M.',
    urgency: 'new',
    slaDate: '2026-02-15',
    createdDate: '2026-02-07',
    source: 'Property management report',
    deepLinks: [
      { target: 'Sheet', label: 'Warranty Log', url: '#sheet-wc-003' },
      { target: 'CompanyCam', label: 'Photos', url: '#companycam-wc-003' },
    ],
    detail: {
      type: 'Warranty',
      claimNumber: 'WC-003',
      unit: 'Unit 308',
      issueType: 'Water stain on ceiling — possible plumbing leak from Unit 408',
      reportedDate: '2026-02-07',
      severity: 'standard',
      assignedTo: 'TBD — Plumbing Sub',
    },
    relatedTaskIds: [],
    qualityAffected: [],
    costCodeRef: null,
    attachments: [],
  },

  // ── Pay App ──
  {
    id: 'PA-005',
    projectId: 'belmont',
    category: 'Pay App',
    subject: 'GC progress billing #5',
    owner: 'Jordan M.',
    urgency: 'watching',
    daysUntilDue: 7,
    slaDate: '2026-02-15',
    createdDate: '2026-02-01',
    source: 'Monthly billing cycle',
    deepLinks: [
      { target: 'Sheet', label: 'Pay App Tracker', url: '#sheet-pa-005' },
      { target: 'Adaptive', label: 'Budget View', url: '#adaptive-pa-005' },
    ],
    detail: {
      type: 'Pay App',
      payAppNumber: 'PA-005',
      contractor: 'SHB Inc. (GC)',
      periodEnd: '2026-01-31',
      amount: 412000,
      retainage: 41200,
      status: 'Under review — waiting for lien waivers',
    },
    relatedTaskIds: [],
    costImpact: 412000,
    scheduleImpactDays: null,
    qualityAffected: [],
    costCodeRef: null,
    attachments: [],
  },

  // ── Pre-Task ──
  {
    id: 'PT-014',
    projectId: 'belmont',
    category: 'Pre-Task',
    subject: 'Concrete pour readiness (Wed)',
    owner: 'Mike S.',
    urgency: 'new',
    slaDate: '2026-02-11',
    createdDate: '2026-02-07',
    source: 'Weekly planning meeting',
    deepLinks: [
      { target: 'Fieldwire', label: 'Task Plan', url: '#fieldwire-pt-014' },
      { target: 'Slack', label: '#field-ops', url: '#slack-field-ops' },
    ],
    detail: {
      type: 'Pre-Task',
      activity: 'Level 4 slab pour — Section B',
      scheduledDate: '2026-02-11',
      crew: 'ABC Concrete — 8 person crew',
      prerequisites: ['Rebar inspection complete', 'MEP sleeves placed and inspected', 'Formwork shoring verified'],
      checklistItems: ['Weather check (48hr)', 'Concrete batch ticket confirmed', 'Pump truck reserved', 'Testing lab on-site'],
    },
    relatedTaskIds: [],
    scheduleImpactDays: 0,
    qualityAffected: [],
    costCodeRef: null,
    attachments: [],
  },

  // ════════════════════════════════════════════════
  // WIELAND — Retail Center (6 tasks)
  // ════════════════════════════════════════════════

  // ── RFI ──
  {
    id: 'GF-RFI-001',
    projectId: 'wieland',
    category: 'RFI',
    subject: 'Storefront glazing detail at corner entry',
    owner: 'Chris L.',
    urgency: 'overdue',
    daysOverdue: 3,
    slaDate: '2026-02-05',
    createdDate: '2026-01-28',
    source: 'Design review',
    deepLinks: [
      { target: 'Smartsheet', label: 'RFI Log #001', url: '#smartsheet-gf-rfi-001' },
      { target: 'Doc', label: 'Glazing Detail', url: '#doc-gf-glazing' },
    ],
    detail: {
      type: 'RFI',
      rfiNumber: 'GF-RFI-001',
      discipline: 'Architectural',
      questionSummary: 'Corner storefront glazing detail not shown — need mullion profile and thermal break spec.',
      designContact: 'SHB Studio — Architect',
      submittedDate: '2026-01-28',
      responseDeadline: '2026-02-05',
      impactedAreas: ['Main Entry', 'Corner Storefront'],
    },
    relatedTaskIds: [],
    scheduleImpactDays: 2,
    qualityAffected: ['Drawing-GF-A101'],
    costCodeRef: '08-00',
    attachments: [
      { type: 'drawing', label: 'Storefront detail A-301', url: '#dwg-gf-storefront-301' },
    ],
  },

  // ── Invoice ──
  {
    id: 'GF-INV-001',
    projectId: 'wieland',
    category: 'Invoice',
    subject: 'Site grading progress billing',
    owner: 'Dana W.',
    urgency: 'due-today',
    slaDate: '2026-02-08',
    createdDate: '2026-02-03',
    source: 'Email — Grading Co.',
    deepLinks: [
      { target: 'Sheet', label: 'Invoice Sheet', url: '#sheet-gf-inv-001' },
      { target: 'Email', label: 'Original Email', url: '#email-gf-inv-001' },
    ],
    detail: {
      type: 'Invoice',
      invoiceNumber: 'GF-INV-001',
      vendor: 'Valley Grading Co.',
      amount: 68500,
      costCode: '31-00 Earthwork',
      submittedDate: '2026-02-03',
      issue: 'Billing exceeds contracted quantity by 12%. Needs field verification.',
      matchStatus: 'partial',
    },
    relatedTaskIds: [],
    costImpact: 68500,
    scheduleImpactDays: null,
    qualityAffected: [],
    costCodeRef: '31-00',
    attachments: [
      { type: 'contract', label: 'Invoice GF-INV-001.pdf', url: '#pdf-gf-inv-001' },
      { type: 'photo', label: 'Grading progress photos', url: '#photo-gf-grading' },
    ],
  },

  // ── Submittal ──
  {
    id: 'GF-SUB-001',
    projectId: 'wieland',
    category: 'Submittal',
    subject: 'Structural steel shop drawings',
    owner: 'Chris L.',
    urgency: 'new',
    slaDate: '2026-02-20',
    createdDate: '2026-02-06',
    source: 'Vendor submission',
    deepLinks: [
      { target: 'Smartsheet', label: 'Submittal Log #001', url: '#smartsheet-gf-sub-001' },
      { target: 'Doc', label: 'Shop Drawings', url: '#doc-gf-steel' },
    ],
    detail: {
      type: 'Submittal',
      submittalNumber: 'GF-SUB-001',
      specSection: '05 12 00 — Structural Steel',
      vendor: 'Ironworks Fabrication',
      submittedDate: '2026-02-06',
      reviewDeadline: '2026-02-20',
      revisionNumber: 0,
      reviewers: ['Chris L.', 'SHB Studio'],
    },
    relatedTaskIds: [],
    qualityAffected: ['Submittal-GF-001'],
    costCodeRef: '05-00',
    attachments: [
      { type: 'drawing', label: 'Steel shop drawings.pdf', url: '#pdf-gf-steel-shop' },
      { type: 'spec', label: 'Spec 05 12 00 — Steel', url: '#doc-gf-spec-0512' },
    ],
  },

  // ── Lead Time ──
  {
    id: 'GF-LT-001',
    projectId: 'wieland',
    category: 'Lead Time',
    subject: 'Structural steel fabrication (AT-RISK 6d)',
    owner: 'Dana W.',
    urgency: 'watching',
    daysUntilDue: 6,
    slaDate: '2026-02-14',
    createdDate: '2026-01-20',
    source: 'Procurement tracker',
    deepLinks: [
      { target: 'Smartsheet', label: 'Procurement Log', url: '#smartsheet-gf-lt-001' },
    ],
    detail: {
      type: 'Lead Time',
      itemDescription: 'Structural steel — main frame and canopy (45 tons)',
      vendor: 'Ironworks Fabrication',
      orderDate: '2026-01-15',
      expectedDelivery: '2026-04-10',
      requiredOnSite: '2026-04-16',
      floatDays: 6,
      riskLevel: 'at-risk',
    },
    relatedTaskIds: ['GF-SUB-001'],
    scheduleImpactDays: 0,
    qualityAffected: [],
    costCodeRef: '05-00',
    attachments: [
      { type: 'contract', label: 'PO — Ironworks Fabrication', url: '#doc-gf-po-ironworks' },
    ],
  },

  // ── Decision ──
  {
    id: 'GF-DEC-001',
    projectId: 'wieland',
    category: 'Decision',
    subject: 'Parking lot surface material',
    owner: 'Dana W.',
    urgency: 'new',
    slaDate: '2026-02-18',
    createdDate: '2026-02-07',
    source: 'Owner meeting',
    deepLinks: [
      { target: 'Smartsheet', label: 'Decision Log #001', url: '#smartsheet-gf-dec-001' },
      { target: 'Doc', label: 'Material Comparison', url: '#doc-gf-parking' },
    ],
    detail: {
      type: 'Decision',
      decisionNumber: 'GF-DEC-001',
      requestedBy: 'Owner — SHB Group',
      options: ['Option A: Standard asphalt', 'Option B: Permeable pavers (green incentive)'],
      deadline: '2026-02-18',
      impact: 'Permeable pavers add $45K but qualify for stormwater credit reducing retention basin size.',
      stakeholders: ['Dana W.', 'Sam W.'],
    },
    relatedTaskIds: [],
    costImpact: 45000,
    scheduleImpactDays: null,
    qualityAffected: [],
    costCodeRef: '32-00',
    attachments: [
      { type: 'spec', label: 'Parking material comparison', url: '#doc-gf-parking-compare' },
    ],
  },

  // ── CO ──
  {
    id: 'GF-PCO-001',
    projectId: 'wieland',
    category: 'CO',
    subject: 'Additional soil export — unsuitable fill',
    owner: 'Chris L.',
    urgency: 'overdue',
    daysOverdue: 1,
    slaDate: '2026-02-07',
    createdDate: '2026-02-01',
    source: 'Geotech report',
    deepLinks: [
      { target: 'Smartsheet', label: 'CO Log #001', url: '#smartsheet-gf-pco-001' },
      { target: 'Sheet', label: 'Cost Estimate', url: '#sheet-gf-pco-001' },
    ],
    detail: {
      type: 'CO',
      pcoNumber: 'GF-PCO-001',
      estimatedCost: 28000,
      costCode: '31-00 Earthwork',
      reason: 'Geotech report identified unsuitable fill in NW quadrant — requires additional export and import of structural fill.',
      submittedBy: 'Valley Grading Co.',
      approvalChain: ['Chris L.', 'Sam W.'],
    },
    relatedTaskIds: [],
    costImpact: 28000,
    scheduleImpactDays: 3,
    qualityAffected: [],
    costCodeRef: '31-00',
    attachments: [
      { type: 'contract', label: 'PCO-001 cost estimate.pdf', url: '#pdf-gf-pco-001' },
      { type: 'spec', label: 'Geotech report — NW quadrant', url: '#doc-gf-geotech' },
    ],
  },

  // ════════════════════════════════════════════════
  // LASALLE — Office Renovation (4 new tasks)
  // ════════════════════════════════════════════════

  // ── RFI ──
  {
    id: 'LS-RFI-001',
    projectId: 'lasalle',
    category: 'RFI',
    subject: 'Existing structural capacity for new mezzanine',
    owner: 'Jordan M.',
    urgency: 'overdue',
    daysOverdue: 2,
    slaDate: '2026-02-06',
    createdDate: '2026-01-30',
    source: 'Structural assessment',
    deepLinks: [
      { target: 'Smartsheet', label: 'RFI Log #001', url: '#smartsheet-ls-rfi-001' },
      { target: 'Doc', label: 'Structural Report', url: '#doc-ls-structural-001' },
    ],
    detail: {
      type: 'RFI',
      rfiNumber: 'LS-RFI-001',
      discipline: 'Structural',
      questionSummary: 'Existing floor slab capacity unknown for proposed mezzanine at east wing. Need structural engineer to confirm load rating before design can proceed.',
      designContact: 'SHB Studio — Structural Engineer',
      submittedDate: '2026-01-30',
      responseDeadline: '2026-02-06',
      impactedAreas: ['East Wing — Level 2', 'Proposed Mezzanine'],
    },
    relatedTaskIds: ['LS-RFI-002'],
    scheduleImpactDays: 5,
    qualityAffected: ['Drawing-LS-S100'],
    costCodeRef: '03-00',
    attachments: [
      { type: 'spec', label: 'Original structural drawings (1987)', url: '#doc-ls-orig-struct' },
      { type: 'photo', label: 'Existing slab condition photos', url: '#photo-ls-slab' },
    ],
  },
  {
    id: 'LS-RFI-002',
    projectId: 'lasalle',
    category: 'RFI',
    subject: 'Existing HVAC duct routing behind ceiling plenum',
    owner: 'Taylor R.',
    urgency: 'new',
    slaDate: '2026-02-17',
    createdDate: '2026-02-07',
    source: 'Site survey',
    deepLinks: [
      { target: 'Smartsheet', label: 'RFI Log #002', url: '#smartsheet-ls-rfi-002' },
      { target: 'Doc', label: 'Survey Notes', url: '#doc-ls-survey-002' },
    ],
    detail: {
      type: 'RFI',
      rfiNumber: 'LS-RFI-002',
      discipline: 'Mechanical',
      questionSummary: 'Existing HVAC ductwork routing above drop ceiling in west wing does not match as-built drawings. Need field survey to confirm routing before demolition plan is finalized.',
      designContact: 'SHB Studio — Mechanical Engineer',
      submittedDate: '2026-02-07',
      responseDeadline: '2026-02-17',
      impactedAreas: ['West Wing — Ceiling Plenum', 'Demo Plan Area C'],
    },
    relatedTaskIds: [],
    scheduleImpactDays: 3,
    qualityAffected: ['Drawing-LS-M200'],
    costCodeRef: '23-00',
    attachments: [
      { type: 'drawing', label: 'As-built mechanical plan (1987)', url: '#dwg-ls-mech-asbuilt' },
    ],
  },

  // ── Invoice ──
  {
    id: 'LS-INV-001',
    projectId: 'lasalle',
    category: 'Invoice',
    subject: 'Hazmat abatement — Phase 1 billing',
    owner: 'Jordan M.',
    urgency: 'due-today',
    slaDate: '2026-02-08',
    createdDate: '2026-02-03',
    source: 'Email — EnviroSafe Abatement',
    deepLinks: [
      { target: 'Sheet', label: 'Invoice Sheet', url: '#sheet-ls-inv-001' },
      { target: 'Email', label: 'Original Email', url: '#email-ls-inv-001' },
    ],
    detail: {
      type: 'Invoice',
      invoiceNumber: 'LS-INV-001',
      vendor: 'EnviroSafe Abatement',
      amount: 38500,
      costCode: '02-00 Hazmat Abatement',
      submittedDate: '2026-02-03',
      issue: 'Scope includes asbestos floor tile removal in areas not yet surveyed. Partial hold recommended.',
      matchStatus: 'partial',
    },
    relatedTaskIds: [],
    costImpact: 38500,
    scheduleImpactDays: null,
    qualityAffected: [],
    costCodeRef: '02-00',
    attachments: [
      { type: 'contract', label: 'Invoice LS-INV-001.pdf', url: '#pdf-ls-inv-001' },
      { type: 'spec', label: 'Hazmat survey report', url: '#doc-ls-hazmat-survey' },
    ],
  },

  // ── Submittal ──
  {
    id: 'LS-SUB-001',
    projectId: 'lasalle',
    category: 'Submittal',
    subject: 'Open office partition system product data',
    owner: 'Taylor R.',
    urgency: 'new',
    slaDate: '2026-02-21',
    createdDate: '2026-02-08',
    source: 'Vendor submission',
    deepLinks: [
      { target: 'Smartsheet', label: 'Submittal Log #001', url: '#smartsheet-ls-sub-001' },
      { target: 'Doc', label: 'Product Data', url: '#doc-ls-partition-001' },
    ],
    detail: {
      type: 'Submittal',
      submittalNumber: 'LS-SUB-001',
      specSection: '10 22 00 — Partitions',
      vendor: 'Steelcase Dealer — Office Interiors Group',
      submittedDate: '2026-02-08',
      reviewDeadline: '2026-02-21',
      revisionNumber: 0,
      reviewers: ['Taylor R.', 'SHB Studio'],
    },
    relatedTaskIds: [],
    qualityAffected: ['Submittal-LS-001'],
    costCodeRef: '10-00',
    attachments: [
      { type: 'spec', label: 'Partition system cut sheets', url: '#doc-ls-partition-cutsheet' },
      { type: 'drawing', label: 'Office layout plan A-110', url: '#dwg-ls-a110' },
    ],
  },
];
